### ISSUE TITLE
Feature request: Make header display configurable

### ISSUE THREAD

**Issue by bbenne10** [custom-cards/spotify-card#102]
Hey! Thanks for the awesome project! It is a great addition to my dashboards :)

However, I am currently fighting to get rid of the header div. 
My use-case is that I have this card stacked in a vertical-stack with the mini-media-player card and the header is redundant.
I can see that there's already a `hide-warning` config option, which guards how the warnings are displayed by altering HTML output.

Would it be too burdensome to also allow a similar config option to disable outputting the header at all?
Styling this card is difficult because of the shadow DOM,
so the easiest solution for anyone else using this sort of approach is to avoid outputting the header at all.

Below is a screenshot of my current arrangement. (No comment on the wide variety of pretty mediocre music on display please ;) )
Note the additional space introduced by the "Spotify" icon. 

If someone can describe how I might go about adding this feature (I'm largely unfamiliar with typescript and entirely unfamiliar with Polymer), I can have a stab at getting a PR ready, if that helps.

![SS](https://user-images.githubusercontent.com/687376/92328199-f356ca00-f02c-11ea-87d4-272234884da6.png)

**Comment by FL550** [comment]
Hey, unfortunately we can't hide the Spotify logo according to their [guidelines](https://developer.spotify.com/branding-guidelines). Maybe we can move the logo to the bottom, but I don't how this would fit into the design of the card.

**Comment by FL550** [comment]
By the way I just saw the play/pause icons aren't allowed either @fondberg

**Comment by FL550** [comment]
But I see your point. Here are some ideas for possible locations for the icon.

Below:
![below](https://user-images.githubusercontent.com/36160004/92330149-05f0f380-f06d-11ea-9d5c-e863d38450fe.png)

Between:
![between](https://user-images.githubusercontent.com/36160004/92330153-0b4e3e00-f06d-11ea-9175-03d7fdb4b427.png)

In the bottom row:
![small-below](https://user-images.githubusercontent.com/36160004/92330156-0db09800-f06d-11ea-911b-23068b32ddcc.png)

In the bottom row with only the icon:
![small-below-icon](https://user-images.githubusercontent.com/36160004/92330157-0e492e80-f06d-11ea-8d48-1543d6ae4114.png)

**Comment by bbenne10** [comment]
That is, in fact, rather unfortunate. 
Seeing the legal ramifications of this, I'll close this if you'd like. 

I suppose I'll have to work around this in another way for my particular use case,
but if we could float the icon right in the last example you provided, I think we'd end up with an unobtrusive compromise.
(with the Spotify brandmark full-right aligning and the shuffle icon to the left of it)

**Comment by FL550** [comment]
No, I definitely see your issue with this and it can be useful for others as well. 

Hm, I'm feel a little uncomfortable with only the spotify icon without the name. Maybe your suggestion combined with the third option is a good idea.

**Comment by bbenne10** [comment]
> Hm, I'm feel a little uncomfortable with only the spotify icon without the name

Why is that? Their official addons utilize this mark and the guidelines say it's acceptable. 
Maybe make it a slightly different color to have it stand out a bit from the other icons in the same row?

**Comment by FL550** [comment]
They say: 
> In cases when the Spotify brand has already been established we simply use the icon on its own.
I'm not sure if it's clear enough that the data is coming from Spotify if we only show a small icon at the bottom. But maybe I am too cautious with this.

**Comment by bbenne10** [comment]
That's fair. 

If I'm being completely honest, I'm not sure that I believe that they really care too deeply about all of this for smaller not-for-profit things like these addons. There's a lot of addons that dont follow these guidelines so strictly and haven't seemed to have a problem (mopidy's spotify support comes to mind) but I'm not running this and I understand your hesitation, as it is a lot of work to be invalidated by a small thing like this

**Comment by FL550** [comment]
I don't want to decide this alone. @fondberg what do you think?

**Comment by fondberg** [comment]
I think it could be ok to have a setting for this as long as it is shown by default

**Comment by FL550** [comment]
Ok, then the small icon in the bottom row. I will make the changes tomorrow.

**Comment by FL550** [comment]
Ok, I just released a new version with the option to hide the header included.

**Comment by bbenne10** [comment]
The implementation is almost perfect :)
I'm now running into some coloring issues, but I'll open a new issue for that

Thanks for this, y'all!
