### ISSUE TITLE
Limit will not exceed 10

### ISSUE THREAD

**Issue by Cassock** [custom-cards/spotify-card#103]
Tried the config below in a list and grid layout and I can go lower than 10, but not higher. Using HA 114.4 on Docker

Card config and screenshot:
![image](https://user-images.githubusercontent.com/15901832/92987835-2a493780-f494-11ea-9f30-2ae3c09fbefe.png)

```random_song: true
type: 'custom:spotify-card'
spotify_entity: media_player.spotify_jp
account: default
playlist_type: featured
country_code: US
always_play_random_song: true
grid_covers_per_row: 5
limit: 15

**Comment by FL550** [comment]
Spotify provides only 10 featured playlists, so this is not a limitation of the card. When you try this with your playlist, you should be able to get more than 10.

**Comment by Cassock** [comment]
https://developer.spotify.com/documentation/web-api/reference/browse/get-list-featured-playlists/ seems to indicate the max is 50

**Comment by FL550** [comment]
This problem lies within the used library `spotipy`. I filed an issue for this.

**Comment by FL550** [comment]
Ok, this is not related with `spotiypy`, it's Spotify itself. Have a look [here](https://developer.spotify.com/console/get-featured-playlists/) to see, that Spotify don't provide more playlists.

**Comment by FL550** [comment]
I'll close this for now.

**Comment by Cassock** [comment]
Thanks @FL550. Followed up at Spotify's community forum and found that the featured playlists quantity fluctuates.
https://community.spotify.com/t5/Spotify-for-Developers/Featured-playlists-limited-to-10/m-p/5039671

**Comment by FL550** [comment]
Thanks for checking this directly with Spotify!
