### ISSUE TITLE
Feature Request: Play/Pause, Back/Next, Volume

### ISSUE THREAD

**Issue by Stupco** [custom-cards/spotify-card#105]
Just a feature request, this card is awesome but I need to use another card to do the above mentioned features, which takes up some valuable screen space.

Would love them to be integrated into this card (if at all possible).

**Comment by FL550** [comment]
I think next/prev playback controls can be included, additional to the play/pause already implemented. 

But I'm unsure about the volume control. I see the benefit, but it can overload the UI. The best position for volume control would be at the bottom of the card. Either on top of the device selection row, or below

**Comment by Stupco** [comment]
It could be an expandable field? Similar to how the Source Select pops up?

Also, if I was to nitpick, can there be some feedback when you have selected a source? Such as a tap colour change or close the source box? It's a tad hard to know if I selected a source and the command sent correctly (hopefully I'm being clear on what I mean)

**Comment by FL550** [comment]
The feedback for selecting a device is included in #106. Thank you for the input!

**Comment by Stupco** [comment]
You, and all the team, are completely awesome! If it wasn't for people like you, we wouldn't have access to such awesome applications!

Happy for you to close this ticket if there is a better way for managing requests.

Keep up the amazing work!

**Comment by FL550** [comment]
Thanks you for your kind words! 

Your request is almost finished in #109.

**Comment by FL550** [comment]
It's released now in v2.3.0!

**Comment by Stupco** [comment]
Awesome quick implementation! You are all awesome!

**Comment by FL550** [comment]
I'm sorry but I had to pull the release back. There are problems with the recognition of the playback state. I need more time for this

**Comment by FL550** [comment]
As this issue is appearing only under certain circumstances I released this again
