### ISSUE TITLE
custom:spotify-card changes volume

### ISSUE THREAD

**Issue by logan893** [custom-cards/spotify-card#113]
**Describe the bug**
Using Spotify Lovelace Card version 2.3.1 installed via HACS, when the card is loaded it sometimes adjusts volume (including when I click "edit" on the card). It often toggles between two previously set volume levels for my speakers, but a few times it has boosted the volume to 99% causing my ears to bleed.

* [ ] Reproducable on a plain lovelace panel without card, style or theme mods
* [ X ] Using latest version of spotcast and spotify-card [ ]
* [ X ] Using latest stable version of Home Assistant
* [ X ] I have Spotify Premium
* [ X ] I have setup the Spotify integration in Home Assistant

**To Reproduce**
1. Play Spotify to a Google Home Speaker Group
2. Change volume of the speaker group
3. Reload the card (refresh page or enter Edit mode for the card)
4. Volume may toggle to previous state (repeatable for a few moments)

**Expected behavior**
Do not attempt to set/change volume when loading the card.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Home Assistant on HassOS 3.13
 - Browser: Chrome
 - Version: 85+
 - HA version: 0.115.6
 - spotcast version: 2.3.1

**Configuration**
Very basic
```
type: 'custom:spotify-card'
limit: 15
spotify_entity: media_player.spotify_account
account: default
playlist_type: discover-weekly
```

**Additional context**
N/A

**Comment by FL550** [comment]
Thank you for your very detailed issue report and sorry for the loud surprise. Unfortunately I have time for this earliest on saturday. But this should be easy to fix.

**Comment by FL550** [comment]
The bug is caused by HA not having noticed the volume change before the reload of the page.  I made a change, so that volume change events are only handled after page load. The change is included in the new release [v2.3.2](https://github.com/custom-cards/spotify-card/tree/v2.3.2)

**Comment by logan893** [comment]
Thanks, tried it out and it... sort of mostly works.

Instead of making a permanent volume change, it seems to now toggle quickly to the previous volume and then back again, where the original behavior was just only toggle back to the previous volume.

**Comment by FL550** [comment]
So the position of the slider changes, but the volume is not set by the card? Do I understand this correct?

The reason for this is, that HA has not notified the change of volume yet and the card reflects this. To prevent this, we could hide the volume slider for a few seconds, but I don't see an option to circumnavigate this behavior of HA.

**Comment by logan893** [comment]
The volume is set and I can hear the change clearly. It toggles back and forth very noticeably on my speakers.

So the issue I had before is:
* I manually change volume of the speaker group I'm casting to, e.g. from 5% to 10%
* Within a few seconds of the volume change, I trigger a loading of the custom:spotify-card card (e.g. click Edit on the card)
Result: Volume changes automatically from 10% to 5% just as the card finishes loading (I do not touch anything on the card)
It seems to always change to what I had previously just changed from.

Behavior after your latest change in v2.3.2:
* I manually change volume of the speaker group I'm casting to, e.g. from 5% to 10%
* Within a few seconds of the volume change, I trigger a loading of the custom:spotify-card card (e.g. click Edit on the card)
Result: Volume changes automatically from 10% to 5% (or something around there, it's too quick to see for sure) just as the card finishes loading (I do not touch anything on the card), and almost instantly changes back again to 10% again.
Same as the previous behavior, it changes the volume only if I had manually and very recently (within a few seconds) changed the volume.

I don't quite understand which is the chicken or the egg here. Do you have to send volume updates to Spotify (if this is how it is done), in any other case than when a user manually changes the slider position?

**Comment by logan893** [comment]
I don't quite understand what's going on, and I haven't looked into your code. I am not ever changing the volume using the custom:spotify-card slider. No other volume slider type integration I have behaves this way.

If I enable the "Hide playback controls" option of the card, it doesn't trigger any volume changes.

**Comment by FL550** [comment]
The volume is set, when the position of the volume slider moves. If the page loads, this is also the case, so I delayed the handling of such events. 

Can you please verify via the developer tools of your browser, that the `handleVolumeChange` method is called and dropped (or not) for the first 2500ms after page load?

**Comment by logan893** [comment]
Your fix does seem to remove any volume change triggering when page is reloaded.

However, since you are only looking at time since page load, this is why the issue can still be reproduced if the Spotify-Card is on a different View tab since switching to this tab makes the card load late but doesn't reload the page, or when I hit "Edit" on the card from page that loaded more than 2.5 seconds ago.

**Comment by FL550** [comment]
Oh, now I understand the problem! I have an idea on how to fix this. I'll keep you informed about the progress.

**Comment by logan893** [comment]
Yep, works well! Great work!

Found another issue with shuffle toggle. I will open a separate ticket for that one.

**Comment by FL550** [comment]
Good to hear!
