### ISSUE TITLE
Shuffle icon state not matching actual Spotify shuffle state if changed after load

### ISSUE THREAD

**Issue by logan893** [custom-cards/spotify-card#115]
**Describe the bug**
Card will show a blue Shuffle state if shuffle is active when card is loaded, but if changing this state from the Spotify web app it's not reflected in the spotify-card that Shuffle is disabled.
Next if toggling Shuffle from spotify-card when in this state, it will look like Shuffle is disabled (blue icon turns to white), but actual Shuffle state is now enabled.

* [ ] Reproducable on a plain lovelace panel without card, style or theme mods
* [x] Using latest version of spotcast and spotify-card [ ]
* [ ] Using latest stable version of Home Assistant
* [x] I have Spotify Premium
* [x] I have setup the Spotify integration in Home Assistant

**To Reproduce**
1. Load spotify-card
2. Change shuffle state from another Spotify app (e.g. web)

**Expected behavior**
Properly reflect current Shuffle state in spotify-card

**Screenshots**

**Environment (please complete the following information):**
 - OS: [Windows 10]
 - Browser: [Chrome]
 - Version: [85]
 - HA version: [0.115.6]
 - spotcast version: [2.3.3]

**Configuration**
N/A

**Additional context**
N/A

**Comment by FL550** [comment]
Is this also the case if you wait some time?

**Comment by logan893** [comment]
If I don't touch the shuffle button on the card further for several seconds then it typically updates the changed state. The behavior sometimes gets buggy though, and it will remain inconsistent. I haven't checked this as much on my PC as I've already closed it for today, but I did a few of these additional checks on my phone. Maybe switching between HA and Spotify screws things up a bit too.

**Comment by FL550** [comment]
The delay in the display of the shuffle state is due to the problems I described in https://github.com/custom-cards/spotify-card/issues/113#issuecomment-708586371.
