### ISSUE TITLE
Draw order/Z order

### ISSUE THREAD

**Issue by Cassock** [custom-cards/spotify-card#12]
Maybe this is a greater issue with HA, but I haven't seen it before. When hovering to select a mediaplayer, the menu is shown under the adjacent card.
![image](https://user-images.githubusercontent.com/15901832/57854194-9854f000-77b5-11e9-9c56-5b420ae49aba.png)

**Comment by fondberg** [comment]
Sorry for not coming back to you on this. I promise I will see if I can fix it soon...

**Comment by Cassock** [comment]
Don't be! I'm not sure this is even specific to this card - when it's adjacent to other cards, it seems to work just fine. 
![image](https://user-images.githubusercontent.com/15901832/58522028-99f6be80-818c-11e9-9848-6fd58be9b5d5.png)

**Comment by fondberg** [comment]
I'm closing this as it is impossible to know the z-index of other cards.
