### ISSUE TITLE
Not found on HACS

### ISSUE THREAD

**Issue by wifi75** [custom-cards/spotify-card#120]
hello the readme maybe it is old, but on my last HA  spoify-card there is not why?

**Comment by FL550** [comment]
The spotify-card is still available in HACS. Have you searched in the "Frontend" tab?

**Comment by wifi75** [comment]
I tryed o find word Spotify, but no spotify card found

**Comment by FL550** [comment]
Have you clicked the orange plus-symbol at the bottom to add a new repository? spotify-card is definitely available in HACS

**Comment by BlackTurtle123** [comment]
> Have you clicked the orange plus-symbol at the bottom to add a new repository? spotify-card is definitely available in HACS

Which repository should we add?

**Comment by FL550** [comment]
After you clicked the orange button, just search for the spotify-card. It is in the list.

**Comment by BlackTurtle123** [comment]
> After you clicked the orange button, just search for the spotify-card. It is in the list.

![image](https://user-images.githubusercontent.com/16037736/98441485-ea52a980-20fe-11eb-864d-c74a2c998727.png)

**Comment by FL550** [comment]
![image](https://user-images.githubusercontent.com/36160004/98444605-e29d0000-2112-11eb-8c59-8a5012ee84d2.png)
Click on "Frontend"

![image](https://user-images.githubusercontent.com/36160004/98444619-fa748400-2112-11eb-9413-2b71c5f7dfdc.png)
Orange plus symbol at right bottom

![image](https://user-images.githubusercontent.com/36160004/98444662-37d91180-2113-11eb-8e80-b6798b4c0c61.png)
Search for spotify

![image](https://user-images.githubusercontent.com/36160004/98444673-44f60080-2113-11eb-947c-4272a1495c15.png)
There it is

![image](https://user-images.githubusercontent.com/36160004/98444684-563f0d00-2113-11eb-8230-ba1d54975863.png)
Click "Install this repository in HACS"

![image](https://user-images.githubusercontent.com/36160004/98444705-6fe05480-2113-11eb-8fc9-e01f05946bd5.png)
Click "Install"

![image](https://user-images.githubusercontent.com/36160004/98444718-81c1f780-2113-11eb-8124-88564f8fefb3.png)
And it's installed

**Comment by BlackTurtle123** [comment]
You are right!
Found it.
Sadly it needs spotcast dependency to work.

**Comment by FL550** [comment]
And is this a problem for you?

**Comment by BlackTurtle123** [comment]
For people not using Chrome casts it contains stuff they will never need.
And that's why I decided not to install it. I won't use it

Op za 7 nov. 2020 19:35 schreef FL550 <notifications@github.com>:
