### ISSUE TITLE
Enhancement: Edit Release to only include required files 

### ISSUE THREAD

**Issue by JulienFloris** [custom-cards/spotify-card#121]
**Describe the bug**
Not an Bug but enhancement tip.
Could the ["Release"](https://github.com/custom-cards/spotify-card/releases) only include the required files and not the entire Repo. Would make installation steps easier to explain and perform for new users.

**Comment by FL550** [comment]
We do not publish the files in releases. The release feature is used to make integration with HACS better. The source code appended to every release is automatically generated by Github and nothing we can customize.

If you want the files of a specific version, you can click on the [version tag of a release](https://github.com/custom-cards/spotify-card/tree/v2.3.4) and download the files you need.
