### ISSUE TITLE
Custom element doesn't exist: spotify-card

### ISSUE THREAD

**Issue by kimme1024** [custom-cards/spotify-card#124]
**Describe the bug**
Tried installing trough HACS, but it auto-closes while installing displaying a red text which disappears too quickly to be able to read it.
I then manually added the files in the correct folder and added it to my lovelace sources.
I restarted HA but the card doesn't show up between the other cards.
When I try to add it manually via YAML it immediately gives the error that the card doesn't exist.
Its probably a stupid mistake but I'm looking into it for a couple of hours now and I just don't see what's wrong.

* [x] Reproducable on a plain lovelace panel without card, style or theme mods
* [x] Using latest version of spotcast and spotify-card [ ]
* [x] Using latest stable version of Home Assistant
* [x] I have Spotify Premium
* [x] I have setup the Spotify integration in Home Assistant

**To Reproduce**
1. Go to 'dashboard'
2. Click on 'add card.'
3. See error

**Expected behavior**
See the card in the list

**Screenshots**
NA

**Environment (please complete the following information):**
 - OS: Raspbian
 - Browser: /
 - Version: /
 - HA version: 0.118
 - spotcast version: 3.4.5

**Configuration**
Add your configuration

**Additional context**

**Comment by kimme1024** [comment]
Suddenly popped up. Very weird!
I'll close this one but I'll have to open another issue for another problem I fear... But I'll dig around a bit first...

**Comment by FL550** [comment]
Great to hear!
