### ISSUE TITLE
Is there a way to connect to non-spotify-connect speakers

### ISSUE THREAD

**Issue by kimme1024** [custom-cards/spotify-card#125]
**Describe the bug**
My goal is to have a Spotify player in my Lovelace UI to control my music. However it should play this music on my Yamaha Network Receiver.
Right now I can only see the web player and the device on which my account is playing music at that moment. When this is the case I can perfectly control everything but I can't start playing from HA.
Is there a workaround so my receiver (which is also connected to HA) can play music controlled by HA trough lovelace UI?

* [x] Reproducable on a plain lovelace panel without card, style or theme mods
* [x] Using latest version of spotcast and spotify-card [ ]
* [x] Using latest stable version of Home Assistant
* [x] I have Spotify Premium
* [x] I have setup the Spotify integration in Home Assistant

**To Reproduce**
1. Go to spotify-card
2. Click on Speaker icon
3. Scroll down to /
4. See error (no speakers appear)

**Expected behavior**
I'd like to see my Yamaha network receiver in the list of available speakers

**Screenshots**
/

**Environment (please complete the following information):**
 - OS: Raspbian
 - Browser: Chrome
 - Version: /
 - HA version: 0.118
 - spotcast version: 3.4.5

**Configuration**
/

**Additional context**
/

**Comment by FL550** [comment]
This is not a bug, as the component only can start playback on chromecast devices or if they are detected by spotify. 
Do you know how the playback on the yamaha receiver is started?

**Comment by kimme1024** [comment]
Ah I see.
It's a Yamaha RX-V675. It has a "Spotify-input" but all that does is open the Spotify app via your phone when selecting it via the companion app.
Mostly I'm just using it via Airplay as this automatically triggers the receiver to turn on but I don't think there's a plugin for that in HA... I guess I'll just have to wait for someone to develop this ;)

**Comment by FL550** [comment]
It seems so, sorry I can't help you with that. 

But maybe it's a good reason to learn to code? ;)

**Comment by kimme1024** [comment]
> It seems so, sorry I can't help you with that.
> 
> But maybe it's a good reason to learn to code? ;)

No problem! Thanks for checking anyway.
As I have zero knowledge about coding I guess it'll take more time for me to learn it than to wait for a solution ;)
