### ISSUE TITLE
Scroll bars in currently playing bar

### ISSUE THREAD

**Issue by davidrustingha** [custom-cards/spotify-card#126]
**Describe the bug**

* [x] Reproducable on a plain lovelace panel without card, style or theme mods
* [X] Using latest version of spotcast and spotify-card [ ]
* [X] Using latest stable version of Home Assistant
* [X] I have Spotify Premium
* [X] I have setup the Spotify integration in Home Assistant

**To Reproduce**
Configure the card (with title and artist visible in card) , start playing a song

**Expected behavior**
I think that the size of the top can be locked since you either want to see the currently playing song, or you'd deselect in while configuring the card

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/62120423/101159095-278e5680-362d-11eb-9813-dbbab674dd18.jpg)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: [e.g. chrome, safari]
 - Version: 86.0.4240.198
 - HA version: 0.118.4
 - spotcast version: v3.4.6

**Configuration**
```
type: 'custom:spotify-card'
account: david
always_play_random_song: true
height: 500
limit: 50
hide_top_header: true
```

**Additional context**

**Comment by FL550** [comment]
This should be fixed in [v2.3.5](https://github.com/custom-cards/spotify-card/commit/275e8cf6c7911d91a34d9441a88f3b833c5bc76d)

**Comment by davidrustingha** [comment]
After updating I the currently playing disappeared entirely..

**Comment by FL550** [comment]
That's strange. I'll have another look tomorrow.

**Comment by FL550** [comment]
Which browser are you using to display the card?

**Comment by FL550** [comment]
Can you please test `v2.3.5-testfix`?

**Comment by davidrustingha** [comment]
Sorry for the late reply. Im using both the companion app and Chrome on Windows. 

I updated to the prefix and in the app it doesnt show the currently playing. I’ll test it on my laptop tonight when I get home

**Comment by FL550** [comment]
Can you please share your raw configuration for the spotify-card with me?

**Comment by davidrustingha** [comment]
Ive checked the card on a Mac and it works just fine there. Seems the problem is only within the app

**Comment by davidrustingha** [comment]
```
type: 'custom:spotify-card'
limit: 50
spotify_entity: media_player.spotify_david
playlist_type: default
account: david
height: 500
display_style: list
hide_top_header: true

```

**Comment by FL550** [comment]
Ok, this seems more like an issue with the app not recognizing the state changes from HA properly.

**Comment by davidrustingha** [comment]
I have checked the app, Chrome on Windows and Chrome on Mac and they all seem to be working correctly. Thanks!
