### ISSUE TITLE
Possibilty to show/hide playlist title in the grid view

### ISSUE THREAD

**Issue by rick00001** [custom-cards/spotify-card#128]
I really would like to have the possibilty to show/hide playlist title in the grid view. If you add playlists with various artists is really hard to tell which playlist is which.

Many thanks if you can add it!

**Comment by FL550** [comment]
This will be implemented soon: #130

**Comment by rick00001** [comment]
Thank you very much! :)

Op zo 20 dec. 2020 om 13:14 schreef FL550 <notifications@github.com>:

**Comment by FL550** [comment]
This is now released!

**Comment by rick00001** [comment]
Thank you very much! And thanks for the feedback!

Op ma 4 jan. 2021 om 17:40 schreef FL550 <notifications@github.com>:
