### ISSUE TITLE
Uninstallable custom:spotify-card with "No client ---- id" error in Lovelace

### ISSUE THREAD

**Issue by falphonso** [custom-cards/spotify-card#129]
**Describe the bug**
Trying to add the Lovelace Spotify Card to my view.
After adding it, the editor only displays the type line in the YAML left side and a warning/error on the right side with the text : 
No client ---- id

Moreover on the left side of the editor, under the YAML text input box, the editor displays "No visual editor available for : spotify-card"
The editor doesn't permit then to save (nor click on visual editor obviously), only cancel.

* [X] Reproducable on a plain lovelace panel without card, style or theme mods
* [X] Using latest version of spotcast and spotify-card [ ]
* [X] Using latest stable version of Home Assistant
* [X] I have Spotify Premium
* [X] I have setup the Spotify integration in Home Assistant

**To Reproduce**
1. Go to Dashboard then the view where you want to add the Lovelace card
2. Click on "Add a card'
3. Type spotify in the editor search box
4. click on the presented "Custom: Spotify Card"
5. See the error

**Expected behavior**
To see the editor with a visual editor presentation of the card and the different options that can be configured through it.

**Screenshots**
x-special/nautilus-clipboard
copy
file:///home/fabrice/Images/20201219_HA_Lovelace_Spotify_Card_error.png

**Environment (please complete the following information):**
 - OS: Home Assistant OS 5.8
 - Browser: tested on Firefox and Chrome on Linux (latest version of Fedora 33 each time) and Firefox on Android (but very old device so certainly not the latest version neither of Android nor Firefox) 
 - Version: latest in HACS v2.3.5-testfix
 - HA version: latest 2020.12.1
 - spotcast version: latest in HACS v3.4.6

**Configuration**
Spotcast integration: done and working
Spotify integration done and working (works very well with media_player)
both of them use config with !secret

**Additional context**

**Comment by falphonso** [comment]
Sorry the copy/paste for the screenshot didn't work. Don't know how to add the screenshot as copy/paste seems to not work from nautilus.

**Comment by falphonso** [comment]
Found it !

![](https://pic.infini.fr/apji5udw/Wwpvc6Qy)

**Comment by FL550** [comment]
Have you tried to refresh your browser cache?

**Comment by falphonso** [comment]
Yes I did.

**Comment by falphonso** [comment]
Well, don't know what to say.....an upgrade of Firefox on fedora 33 later and it seems to work now (not really sure the update of Firefox itself was really the solution to my problem, but.....well)

Closing as the problem (which seems to not really been one in first place), feel free to re-open if needed.

And anyway, thank you for this (Lovelace Card and Spotcast) in first place !

**Comment by FL550** [comment]
Great to hear! My first guess was, that this might be a caching issue. And the browser update confirms this a bit. But anyway thanks for your feedback!
