### ISSUE TITLE
Login not shared through HA among devices

### ISSUE THREAD

**Issue by Nihvel** [custom-cards/spotify-card#13]
It might not be an issue but unfortunately it is annoying.
Wherever this issue falls to, it can be so reproduced:

1. After following the installation guide, the user is presented with this below picture:
https://github.com/custom-cards/spotify-card/blob/master/spotify-card-authenicate.png
2. The user Logs in. His playlists (if any) appear.
3. The user has other devices. He wants to use this same HA card.

**Expected behaviour**:
For each device he has, he is presented the same HA Lovelace dashboard (therefore Spotify card) whose user is logged in.

_Example_:
Home Assistant has a user "tablet". User tablet is logged in on a tablet device. He logs in for the first time to Spotify through spotify-card. User tablet logs in on another device. _He is presented the same spotify-card already logged in_.

**Current behaviour**:
For each device he has, he must log in to Spotify.

_Example_:
Home Assistant has a user "tablet". User tablet is logged in on a tablet device. He logs in for the first time to Spotify through spotify-card. User tablet logs in on another device. _He has to repeat the login_.

**Notes not part of the issue**:
Thanks for your work! It is a wonderful project.

**Comment by fondberg** [comment]
Login can't be shared between devices because the token is required per card. If someone rewrote the spotify_mediaplayer component to use a descent spotify api I can switch to use that but in the meantime this will use spotifys apis directly.

However, you are right that it should not be required to click the authorize button all the time. I will check if I can fix this so it is done automatically but right now I am pressed for time as I will get a new child coming in june and I have limited time for open source projects. If you know some basic javascript you can try to fix this yourself, I believe a check if the token if stale but exists and an automatic re-auth call would do the trick...

**Comment by fondberg** [comment]
The authorize button should not appear in the latest. I can't reproduce it. Can you test and make sure you have the latest release?

**Comment by Nihvel** [comment]
Hey, didn't expect a quick fix! Thanks for thinking at this. 
So, I tried both with MASTER and LATEST loaded as per installation instruction (before I was only on MASTER). 
- I opened a incognito window and logged in as 'tablet' user. The button "authenticate" appears. 
- I also opened a new window on another browser, not incognito this time, logged in again as tablet and the same authenticate window appear.
- I logged as another user, a ADMIN user (tablet is not admin) but the same behavior happens: It shows the authenticate button.

Do you maybe have proper instructions? Probably I miss some points, not sure.
Thanks!

**Comment by fondberg** [comment]
If you read my original answer carefully you see that the token is stored locally per browser per device (as per spotify auth docs). That means you can't expect it to login across browsers and devices

**Comment by Nihvel** [comment]
True, I misinterpreted your answer and thought you found some magic trick that allowed my original answer/issue to be addressed. 
The tablet yesterday was still showing the AUTH button, this happens after i wake it up from screen off (even though it should auto-refresh when screen is off...). 
When I manually refresh HA dashboard, your plugin goes from asking for authentication to authenticated and shows the playlists. I guess it is here you are working on. Also this "bug" is annoying, but it only happens in the tablet (android 5.1) and wherever there's android, also v. 7. 
Fedora and Windows (some other PCs of mine) work as intended.

**Comment by fondberg** [comment]
I think the problem you encounter is the same as this one https://github.com/custom-cards/spotify-card/issues/10

Basically if left open it will stop working until a refresh of the page

**Comment by Nihvel** [comment]
Yes, this is the problem I face. The tablet is set to auto refresh every 20 minutes. The main tab that lovelace shows (the one I use the most) is not the tab where your Spotify card is. When I tap on the Spotify tab, I have to manually refresh to re-authenticate it. 
It doesn't bother me much but it's great that this is listed in your checklist already. I have no rush ;) 

About the original issue instead, I can consider this issue as "closed". I understand there is no solution at the moment. I'm glad that you took some time to review it and provided me your feedback.
