### ISSUE TITLE
Cannot load lovelace card

### ISSUE THREAD

**Issue by cerberek** [custom-cards/spotify-card#133]
I installed this custom card over HACS.
As well I added this location to my lovalace.yaml file
When I add card with config
```
cards:
  - type: 'custom:spotify-card'
```
I can see in logs error
```
ERROR (MainThread) [frontend.js.latest.202012291] <my_url>/local/community/spotify-card/spotify-card.js:941:377 Uncaught SyntaxError: Unexpected token 'export'
```

**Comment by FL550** [comment]
Which browser are you using?
[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export#browser_compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export#browser_compatibility)

**Comment by mdbraber** [comment]
Same error here, on both Safari and Chrome. Seemed to work before...

**Comment by kochen** [comment]
Experiencing the same on both latest Chrome & Safari
HA: 2021.3.4

**Comment by mdbraber** [comment]
@!kochen what fixed it for me was to specify `type: module`

```
resources:
  - url: /local/spotify-card.js
  - type: module
```

**Comment by fondberg** [comment]
Is this still an issue?

**Comment by rjenx** [comment]
I know this is closed but I am seeing the same error and mdbraber's solution is not the issue for me.
