### ISSUE TITLE
Not sure when, but it stopped working lately

### ISSUE THREAD

**Issue by etxttul** [custom-cards/spotify-card#141]
**Describe the bug**
It appears it can not find any media devices.

* [Y ] Reproducable on a plain lovelace panel without card, style or theme mods
* [Y ] Using latest version of spotcast and spotify-card [ ]
* [Y ] Using latest stable version of Home Assistant
* [Y ] I have Spotify Premium
* [Y] I have setup the Spotify integration in Home Assistant

**To Reproduce**

**Expected behavior**
I expected it to work as it did before :-)

**Screenshots**
![bild](https://user-images.githubusercontent.com/58366158/110167316-e0fbf400-7df5-11eb-81ca-3eee4bf1b0b2.png)
I can't snip it, but when hovering over "choose player" it says no devices found.

**Environment (please complete the following information):**
 - OS: Hassio
 - Browser: firefox edge, upgraded to latest versions.
 - Version: [ ]
 - HA version:  2021.3.xx
 - spotcast version: 3.4.7 latest version

**Configuration** I took most of it out when it stopped working to start from scratch
      - type: 'custom:spotify-card'
        # grid_covers_per_row: 4
        # limit: 30
        # height: 500
        # overflow-y: scroll
        # display_style: grid
        # default_device: media_player.stereon
        # # always_play_random_song: true
        # device: media_player.stereon
        # filter_devices:
        #   - media_player.huset
        #   - media_player.lilla_sovrummet
        #   - media_player.samsung_ue46f6320
        #   - media_player.soffan_hoger
        #   - media_player.soffan_vanster
        #   - media_player.sovrum_2
        #   - media_player.stereon_hoger
        #   - media_player.vardagsrummet

**Additional context**

**Comment by etxttul** [comment]
Problem solved, needed to update SP_DC and SP_key in spotcast integration

**Comment by MarioPinto** [comment]
> Problem solved, needed to update SP_DC and SP_key in spotcast integration

Are you sure that this is what solved it?
I have the exact same problem but my SP_DC and SP_key are up-to-date...

**Comment by etxttul** [comment]
Yup, I'm sure!

**Comment by fondberg** [comment]
Is this still an issue?
