### ISSUE TITLE
Feature request: playlist_type: recent_played

### ISSUE THREAD

**Issue by alnavasa** [custom-cards/spotify-card#142]
**Describe the Feature request:**
playlist_type: recent_played. Having this setting limited to just default (all playlists), featured, or weekly discovery is great, but adding the benefit of recently played playlist will rock the card.
In My case I like my playlists, and other peoples, and they are not arranged in the order that I normally play. 
**Usually when I open Spotify it suggests the last x played playlists, and I am used to that.**

```
playlist_type: <optional featured|discover-weekly> Change type of playlists shown. Default are your normal playlists.
```

```
playlist_type: recent_played

```

**Comment by fondberg** [comment]
What is the uri for this?

**Comment by fondberg** [comment]
I don't think they have this in their APIs. If you find something open a new issue with technical details
