### ISSUE TITLE
The choose player function is not completed until doing a refresh of the page.

### ISSUE THREAD

**Issue by etxttul** [custom-cards/spotify-card#146]
**Describe the bug**
When choose player, the music the first song in the first playlist starts in choosen the player (fine) , but the player don't appear as choosen in the card until I reload the page or do a refresh in HA. This means if I don't do refresh of the browser/HA, I can't select the playlist I want to listen to.
* [ ] Reproducable on a plain lovelace panel without card, style or theme mods
Yes, Even when reducing the card to a minimal configuration I get the same problem.
Config:
      - type: 'custom:spotify-card'
* [ ] Using latest version of spotcast and spotify-card [ ]
Using the latest versions visible in HACS
Start Spotify on chromecast v3.5.2
Spotify Lovelace Card v2.3.7
* [ ] Using latest stable version of Home Assistant
Yes!
![bild](https://user-images.githubusercontent.com/58366158/114989240-85626300-9e97-11eb-9c9b-fad3a88a4fcc.png)
* [ ] I have Spotify Premium
Yes
* [ ] I have setup the Spotify integration in Home Assistant
Yes
**To Reproduce**
Select a player by in 'choose player' Music start playing, but the player don't appears as choosen and no new playlist can be choosen until until the page is refreshed.

**Expected behavior**
I would expect the choosen to be visible directly and that it would be possible to choose a new playlist.

**Screenshots**

**Environment (please complete the following information):**
See above

**Configuration**
Add your configuration
Config:
      - type: 'custom:spotify-card'

**Additional context**
I thought it might be browser related, but I tested it on
- HA android app
- firefox
- chrome
- edge
- vivaldi
- opera
All with the same result.

Best Regards
Tobe

**Comment by fondberg** [comment]
Is this still an issue?
