### ISSUE TITLE
can't male device: working

### ISSUE THREAD

**Issue by thib5** [custom-cards/spotify-card#15]
Hi I try to pre-select a device but it does not seams to work ..

this is my code :

          - type: 'custom:spotify-card'
            client_id: sodiujsodlsaiujo8u29ajkof9oujd9fafp9a3jokdpa2
            limit: 5
            device: Salon GoogleHome

**Comment by fondberg** [comment]
Logs plz

**Comment by jaburges** [comment]
@thib5 is the device  'Salon Googlehome'? 
check states in the dev panel, pretty sure it will need to be a `media_player.<yourdevicename>`

**Comment by fondberg** [comment]
No. As this is a spotify device it is the name of the Spotify Connect device. 

Preselecting only works if the device is a Spotify connect device. That means it can't be a chromecast device

**Comment by fondberg** [comment]
Closing as the name applies it was a google home device which requires chromecast to start spotify
