### ISSUE TITLE
Request on hyperlink

### ISSUE THREAD

**Issue by v-sante** [custom-cards/spotify-card#154]
Amazing card and I was so totally would implement this change if I knew how, but short request.

The spotify icon on the card presently links to: https://www.spotify.com/

However, assuming everyone who uses this card has an account and would only want to go to the website to access the webplayer, could I suggest this link instead:  https://open.spotify.com/

That would take you straight to where you want to be...!

Just a thought.

**Comment by fondberg** [comment]
I guess that is doable

**Comment by fondberg** [comment]
https://github.com/custom-cards/spotify-card/releases/tag/v2.3.9
