### ISSUE TITLE
HA iOS app doesnt work

### ISSUE THREAD

**Issue by jaburges** [custom-cards/spotify-card#16]
Hey there, 
I have it working on chrome and edge:chromium - and its great.

However, its not authenticated in the mobile app (the newer iOS app). I'm assuming as there is no URI to return to?

**Comment by fondberg** [comment]
I'm not sure what you mean because I don't have iOS. Is this an app or a browser?

**Comment by jaburges** [comment]
Yes the official Home Assistant iOS app. 
Even after authenticating on a browser, i'm still asked to authenticate on the mobile iOS app.

**Comment by fondberg** [comment]
Unless the app supports cookies, webstorage and OATH redirects I'm afraid it won't work.

**Comment by jaburges** [comment]
Ah ok, will share the info.
