### ISSUE TITLE
Wallpanel support

### ISSUE THREAD

**Issue by Lenny5156** [custom-cards/spotify-card#20]
I'm trying to authenticate this card on my tablet with [WallPanel](https://thanksmister.com/wallpanel-android/) from thanksmister but nothing happens. Except I double click it then it shows this error: "response_type must be code or token"

**Comment by fondberg** [comment]
This card requires the browser to support redirects for the authentication and I'm pretty sure it was written on the community forum page that WallPanel doesn't support it
