### ISSUE TITLE
Spotcast breaking change V4.0 and upwards.

### ISSUE THREAD

**Issue by mikevanes** [custom-cards/spotify-card#217]
Starting from spotcast v4.0 the spotify-card is broken. As this project is now abandoned, i made a fork which contains the fix. 
https://github.com/mikevanes/spotify-card-v2 The fork also adds the recently-played playlist option.  Currently not available through HACS yet, will try to get this working. 

**For any issues or comments please use the fork as I will not reply in here anymore.**

**Comment by stanogustafik** [comment]
thank you very much! this solved the lovelace problem... please, will you keep updating this card in the future?

**Comment by mikevanes** [comment]
I will try my best.

**Comment by IIIdefconIII** [comment]
do we need spotify premium for this?

**Comment by mikevanes** [comment]
I am not sure, you can try I think not.

**Comment by DaveStLou** [comment]
Thanks for updating this card. Since switching over I am getting this error when I click on a playlist to play:

Failed to perform the action spotcast/start. Either entity_id or device_name must be specified

I am using the same yaml I did under the old spotify-card version including "default_device".

I have to click a device and then a playlist. In otherwords it seems to be ignoring the default.

Is there something new I need to do under this version?

**Comment by mikevanes** [comment]
Could you post your YAML? I'm leaning a bit towards this being a spotcast issue rather than a spotify-card issue, seeing the changes I had to make. But lets see.  Also what versions are you using exactly? @DaveStLou

**Comment by DaveStLou** [comment]
Here's my yaml:

type: custom:spotify-card-v2
limit: 30
hide_playback_controls: true
hide_top_header: true
visibility:
  - condition: state
    entity: input_boolean.showspotifycard
    state: "on"
always_play_random_song: true
display_style: list
filter_devices:
  - Tap
  - Chromecast
height: 205
default_device: All Audiocast

I'm on Spotcast Version v4.0.0.

With all of the Spotify issues caused by this update, I'm not sure what might be causing the issue.

**Comment by mikevanes** [comment]
Could you try using just, and perhaps show some screenshots of the error your encountering, I have no way to reproduce at the moment. Also please format your code in a code block so that it is readable and usable by me. 

`- type: custom:spotify-card-v2` 

Nothing else, this should work. Could you also specify your spotcast version. I have a strong tendency towards this being a spotcast issue instead.

**Comment by DaveStLou** [comment]
Apologies for messy yaml above. I should have known better than to try to respond from my phone.

I am on Spotcast v4.0.0

Here my yaml for the primary use for the Spotify Card v2

```
type: custom:spotify-card-v2
limit: 30
hide_playback_controls: true
hide_top_header: true
visibility:
  - condition: state
    entity: input_boolean.showspotifycard
    state: "on"
always_play_random_song: true
display_style: list
filter_devices:
  - Tap
  - Chromecast
height: 205
default_device: All Audiocast
```

However, when I use only 
```
type: custom:spotify-card-v2
```
I get the same error when I click a playlist.

Here's a screenshot with the error at the bottom:
![Screenshot 2024-11-10 145759](https://github.com/user-attachments/assets/ab54e1d4-ce95-43fc-9c4a-3dfc65f95d28)

**Update:** It seems the error does not occur is I clear the chromecast playlist before requesting a new playlist. Seems like more of a workaround but at least it's functional.

**Comment by IIIdefconIII** [comment]
my card worked 2 days ago but all sudently got broken :(

**Comment by mikevanes** [comment]
I will look into this tonight or tomorrow most likely a small fix

**Comment by IIIdefconIII** [comment]
> I will look into this tonight or tomorrow most likely a small fix

that would be lovely!

**Comment by mikevanes** [comment]
@IIIdefconIII @DaveStLou This should now be fixed. Could you open an issue on the new repo next time? This makes tracking easier for me.

**Comment by ahaverty** [comment]
@mikevanes you need to enable issues on your fork in settings 👍

**Comment by IIIdefconIII** [comment]
> @IIIdefconIII @DaveStLou This should now be fixed. Could you open an issue on the new repo next time? This makes tracking easier for me.

i would love to help in any part, as i have a brain unjury, what should/can i do now? waiti for the nexts ha update?

**Comment by mikevanes** [comment]
My bad should now be enabled. @ahaverty 

@IIIdefconIII Nothing the new code can be downloaded in the releases tab. https://github.com/mikevanes/spotify-card-v2/releases/tag/V1.1 Updating still needs to be done manually, remove the old files in spotify-card-v2 folder and place the new downloaded files there. 

I'll do my best to get it on the HACS store to make installing the new versions less of a hassle.

**Comment by IIIdefconIII** [comment]
> My bad should now be enabled. @ahaverty
> 
> @IIIdefconIII Nothing the new code can be downloaded in the releases tab. https://github.com/mikevanes/spotify-card-v2/releases/tag/V1.1 Updating still needs to be done manually, remove the old files in spotify-card-v2 folder and place the new downloaded files there.
> 
> I'll do my best to get it on the HACS store to make installing the new versions less of a hassle.

i will try right now thanks, i never hjad that v2 folder only the spotify-card folder in /www/community/ sry i have ABI and im kinda lost some times ill try now how far i come

**Comment by IIIdefconIII** [comment]
doesnt work do
![image](https://github.com/user-attachments/assets/c4b3097c-79bf-47e2-9c68-8acd47f1d821)
yes restarted ha 2 times, not the server itsel;lf

**Comment by IIIdefconIII** [comment]
![image](https://github.com/user-attachments/assets/dbb2146c-26d0-4365-b9ee-b271a83e0ac0)

**Comment by IIIdefconIII** [comment]
i might be doing someting terrable wrong but even after a server reboot, i was maybhe it didnt propegate the files with just a vm restart, but its still not working on my end only the normal spotify vard which is even broken

**Comment by mikevanes** [comment]
@IIIdefconIII can you show the contents of the folder? Can also be a caching issue, trying in an incognito window might fix the issue. Otherwise I'll try to reproduce myself tomorrow

**Comment by IIIdefconIII** [comment]
> @IIIdefconIII can you show the contents of the folder? Can also be a caching issue, trying in an incognito window might fix the issue. Otherwise I'll try to reproduce myself tomorrow

mm that coult bee, didnt think about that ill try right now

**Comment by IIIdefconIII** [comment]
![image](https://github.com/user-attachments/assets/3a01c216-6ed9-4af5-93db-272bf1234667)

**Comment by IIIdefconIII** [comment]
removed cache and koekjes, had to re-loging so sure that thats done
![image](https://github.com/user-attachments/assets/a2510df7-0ab9-497c-a262-cbce0516c63f)

still not showing up

**Comment by IIIdefconIII** [comment]
> @IIIdefconIII can you show the contents of the folder? Can also be a caching issue, trying in an incognito window might fix the issue. Otherwise I'll try to reproduce myself tomorrow

cool, let me know tmrow i can provide a teamveiwer acces for u. i think im not the only one thats stuck on this part

**Comment by ahaverty** [comment]
> > @IIIdefconIII can you show the contents of the folder? Can also be a caching issue, trying in an incognito window might fix the issue. Otherwise I'll try to reproduce myself tomorrow
> 
> cool, let me know tmrow i can provide a teamveiwer acces for u. i think im not the only one thats stuck on this part

Inspect element your dashboard and check console logs to see what's going wrong. I saw the same error, but it was because I right clicked on the two files and saved-as from GitHub, which actually downloaded them as html. My fix was making sure i downloaded both files as raw from GitHub, and reuploaded to them to my HA to fix, then hard reset of chrome cache.

**Comment by mikevanes** [comment]
Also don't forget to add it as a module, I'm using yaml mode I'm not sure how to do this in the UI.

**Comment by IIIdefconIII** [comment]
Also don't forget to add it as a module, I'm using yaml mode I'm not sure how to do this in the UI.

1> Make sure the files ar in the correct place:
![image](https://github.com/user-attachments/assets/2f6576bd-d058-4787-8756-5ca5e112c7b4)

2>
Right upper corner on the dashboard hit menu -> 
![image](https://github.com/user-attachments/assets/c735b5fa-a810-4d5a-b78e-73e50c95c7a5)
Manage Resources

3>
fill in the local url:
![image](https://github.com/user-attachments/assets/1e32a85a-5aa4-4fe7-bc87-21bf22c17be1)

Done that now going to restart it and see the result

**Comment by IIIdefconIII** [comment]
Its working!!!

![image](https://github.com/user-attachments/assets/5ee048d4-0efd-4db9-bfa8-6c432869598b)


Thanks so much!!!

**Comment by IIIdefconIII** [comment]
![image](https://github.com/user-attachments/assets/78df75db-1101-4e13-aab7-9e7d535eccac)

**Comment by IIIdefconIII** [comment]
Only the media buttons "still" not works and that not a huge deal for me:)

![image](https://github.com/user-attachments/assets/b312065a-c115-4068-ad1a-7d9034a76fe0)

**Comment by mikevanes** [comment]
I will look into that, but judging from the error is might be an issue with your device.

**Comment by IIIdefconIII** [comment]
> I will look into that, but judging from the error is might be an issue with your device.

Ok i will now check the nvidia shield, im pklaying now from sporify on windows ill report back  in a few min

EDIT, can succesfully swap to nvidia shhield and playing there now, but nope the button disagree to work

EDIT2:
![image](https://github.com/user-attachments/assets/71fa479c-3b8b-42cf-8354-5b34f666ef8c)


Check all devices pushing a playlist just work paying on all devices but just the buttons giving me that fedback i have send above

Last edit: swapping the sound to different devices work flawless! which i great!

**Comment by mikevanes** [comment]
I do think it is related to either spotcast not supporting it or a limitation, as the functionallity does works for me.

**Comment by IIIdefconIII** [comment]
> I do think it is related to either spotcast not supporting it or a limitation, as the functionallity does works for me.

i guess its not working as i gave up spotify premium a week or 2 ago. so il will recheck once im back on premium the 23 this month

lemme guess you have premium xD

**Comment by spider7611** [comment]
Not working for me. Everything is there where it should.

**Comment by mikevanes** [comment]
> > I do think it is related to either spotcast not supporting it or a limitation, as the functionallity does works for me.
> 
> 
> 
> i guess its not working as i gave up spotify premium a week or 2 ago. so il will recheck once im back on premium the 23 this month
> 
> 
> 
> lemme guess you have premium xD

I do have premium indeed.

**Comment by mikevanes** [comment]
> Not working for me. Everything is there where it should.

Some information as to what is not working and your config would be needed, it is working for multiple people so most likely it should work.

Also I'm gonna close this thread. For any issues/ideas please raise an issue/discussion on the fork.

**Comment by spider7611** [comment]
![chrome-capture-2024-10-13](https://github.com/user-attachments/assets/2e47f4d3-354c-4090-a550-e69d2e1623d1)
![chrome-capture-2024-10-13 (1)](https://github.com/user-attachments/assets/87ed6031-c1d0-4b40-a706-5e0582f5520c)
![chrome-capture-2024-10-13 (2)](https://github.com/user-attachments/assets/89414dba-c5ce-40f6-976b-8ffc772400b3)

**Comment by IIIdefconIII** [comment]
> ![chrome-capture-2024-10-13](https://private-user-images.githubusercontent.com/45290475/385669117-2e47f4d3-354c-4090-a550-e69d2e1623d1.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0ODg4MzAsIm5iZiI6MTczMTQ4ODUzMCwicGF0aCI6Ii80NTI5MDQ3NS8zODU2NjkxMTctMmU0N2Y0ZDMtMzU0Yy00MDkwLWE1NTAtZTY5ZDJlMTYyM2QxLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QwOTAyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOWU5YWNiMGY5NTZmYWExNDdiNmY0ZWQ0NTg0YjU3MDdjNmNlNzk2ZjQ4NzJiMmRjOTA2Zjc2MGNjMzBhOTNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.H7NlkjXM7VjCX59JrmbWY9cRqFJef1aEk0lP9P18ors) ![chrome-capture-2024-10-13 (1)](https://private-user-images.githubusercontent.com/45290475/385669125-87ed6031-c1d0-4b40-a706-5e0582f5520c.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0ODg4MzAsIm5iZiI6MTczMTQ4ODUzMCwicGF0aCI6Ii80NTI5MDQ3NS8zODU2NjkxMjUtODdlZDYwMzEtYzFkMC00YjQwLWE3MDYtNWUwNTgyZjU1MjBjLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QwOTAyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjliOTc2YjBkZTA2MzlmNDcyODhmZGJjOWFkM2FjODBlMWM0ZDdkZmU3YzhmMGE1YjZmZWMxMzBiM2JlNjI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.05X33tN_BpBdvvd-bC4ckx4091AVv-gmaHcCXbsqARk) ![chrome-capture-2024-10-13 (2)](https://private-user-images.githubusercontent.com/45290475/385669131-89414dba-c5ce-40f6-976b-8ffc772400b3.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0ODg4MzAsIm5iZiI6MTczMTQ4ODUzMCwicGF0aCI6Ii80NTI5MDQ3NS8zODU2NjkxMzEtODk0MTRkYmEtYzVjZS00MGY2LTk3NmItOGZmYzc3MjQwMGIzLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QwOTAyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZWRkYjYyMDhiYTljZTkzMzJlZDVmMTFlMDUxNTgwMzgxNmY5NGIzNTU2N2E5N2Y5NzQ1YzU4YTUxMmUzNmRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WZHHrcKH6czEuLquPDMv8_gkD4wkS8KWTM8uylfzKSw)

just a few post above i explained how to fix this
https://github.com/custom-cards/spotify-card/issues/217#issuecomment-2470849904

**Comment by IIIdefconIII** [comment]
> Not working for me. Everything is there where it should.

https://github.com/custom-cards/spotify-card/issues/217#issuecomment-2470849904

**Comment by spider7611** [comment]
I did everything as it should and read it back. It just can't find spotify-card-v2. I guess you can see the pictures I posted that everything is there and as it should be?! I restarted Home Assist several times and also stopped and restarted docker several times. I also deleted the cache from the browser and it didn't help.

**Comment by IIIdefconIII** [comment]
> I did everything as it should and read it back. It just can't find spotify-card-v2. I guess you can see the pictures I posted that everything is there and as it should be?! I restarted Home Assist several times and also stopped and restarted docker several times. I also deleted the cache from the browser and it didn't help.

did u also do this?
https://github.com/custom-cards/spotify-card/issues/217#issuecomment-2470849904

**Comment by spider7611** [comment]
Yes! That's what I'm saying.

**Comment by mikevanes** [comment]
It can't find the card for some reason so things to try:

1. Remove the folder and repaste the downloaded code.
2. Clear cache.
3. Try incognito.
4. Provide some screenshots also of the import.
5. In the .js file there should be some reference to the v2 card can you double check that?
6. Is the card showing in the cards when adding a new card into your dashboard?

Else I'm a bit lost on what's going wrong but somehow the import is not working. The card code is not at fault here I'm pretty sure.

**Comment by IIIdefconIII** [comment]
can i gentyl ask if there is a wip for the buttons not working? great car so far!

**Comment by mikevanes** [comment]
Did you verify if the is related to not using Spotify premium, there are some limitations to free accounts, one of which is not being able to skip songs.

**Comment by IIIdefconIII** [comment]
nice trick to make the card even look better:
![image](https://github.com/user-attachments/assets/2b4f2669-a5f6-4ffc-b74e-d7d244aa8b74)
```
type: custom:spotify-card-v2
card_mod:
  style: |
    ha-card {
    background: none !important;  
    border: none !important;
     }
```
