### ISSUE TITLE
once play is started , it cant be stopped 

### ISSUE THREAD

**Issue by gnkarn** [custom-cards/spotify-card#22]
pause is missing from the  interface , only play  is available no stop, no pause .

**Comment by fondberg** [comment]
I am reluctant to add too much player logic into the card but if this something many people want it can of course be done

**Comment by fastcolors** [comment]
no real need for it if you have all the player cards setup... I agree with @fondberg in leaving player logic out of this and keep a plain "select playlist"

**Comment by fondberg** [comment]
It is quite small but then it feels like skip forward and back should be implemented too...
