### ISSUE TITLE
still asking for spotcast

### ISSUE THREAD

**Issue by fastcolors** [custom-cards/spotify-card#23]
Hi,
when trying to push stream to idle cast device (any of them) error is raised:

Fallita chiamata a servizio spotcast/start . Service not found.

> Failed call to spot cast/start service. Service not found.

Everything perfect with spot cast in place.

tried both 
dist download versions 3170aacc56a1597f411d5d6b6dbd96bcfcbf749d
and 
https://cdn.jsdelivr.net/gh/custom-cards/spotify-card@1.8/dist/spotify-card.umd.js

(even @1.9 just in case)

great job anyways!!
cheers.

**Comment by fondberg** [comment]
You need to install spotcast https://github.com/fondberg/spotcast
