### ISSUE TITLE
Redirected to login page

### ISSUE THREAD

**Issue by RolandGoud** [custom-cards/spotify-card#25]
Hi,
Seems I'm missing something...

Whenever I try to authorize, the login page is where i'm redirected to. After logging in I am not authorized. (the auth redirect URi is correct) and I have authorized the component using the api part of the url succesfully before.

Somhow using the same url  but instead using the view url is not working. I even renamed the url for the view to mathc the example:

/lovelace/media

also added 

/lovelace/media/ 

just to be sure

any ideas what is wrong?

**Comment by fondberg** [comment]
This question is better asked in the forum (and this particular is already answered in the forum many times)
