### ISSUE TITLE
Doesn't work with all browsers

### ISSUE THREAD

**Issue by tomoqv** [custom-cards/spotify-card#3]
custom: spotify-card displays fine in Chrome and Vivaldi (Chromium), but not in Firefox or in Morph browser on [Ubuntu Touch](https://ubports.com/) based on [QtWebEngine](https://wiki.qt.io/QtWebEngine). In the latter browsers I get “Custom element doesn’t exist: spotify-card”.

**Comment by fondberg** [comment]
I will need to look into something like rollup and babel to get transpile an ES5 module. If anyone has a handy setup I would love to get input

**Comment by MichaelRoxin** [comment]
I can't get this to work. 

I have added the client id and set my redirect to https://<your public home assistant hostname>:8123/lovelace/media in the  Spotify Developer web. 

But when I click on authenticate i get to an invalid url. 

What to do?

**Comment by fondberg** [comment]
@MichaelRoxin That is not related to this issue. Open a new issue and try using latest Chrome and if it still fails copy the output from the devtools->console

**Comment by fondberg** [comment]
I've fixed a transpiled version now. Please try with this: `https://cdn.jsdelivr.net/gh/custom-cards/spotify-card@1.2/dist/spotify-card.umd.js`

**Comment by tomoqv** [comment]
Yes, it appears to work. Some browsers need several clear cache and refresh, but eventually it works!
