### ISSUE TITLE
Two accounts

### ISSUE THREAD

**Issue by ThirteenTX** [custom-cards/spotify-card#32]
Is there anyway to have two accounts set up with a card? My wife wants her own card for her own account. Seems like only 1 log in per instance I guess. Just wanting to confirm or maybe I am missing a work around.

**Comment by uSpike** [comment]
I tried making an instance of the card in a different view, and that did not work.

**Comment by teejaynl01** [comment]
If it would be possible to pass the account alias through to spotcast, that would be great!

**Comment by fondberg** [comment]
Unfortunately not on the same browser instance. You can have how many you like as long as they are on different browsers

**Comment by teejaynl01** [comment]
thats exactly what i'm trying to accomplish; 2 tablets each with their own view and own spotify card, however as far as i can tell they both have to use the same main spotify account - instead of them each using their own spotify account. Are you saying that there's a way for each tablet to use its own spotify account somehow?

**Comment by fondberg** [comment]
I forgot I only implemented it in spotcast and not in this card.
I quickly hacked together something which is not all all tested, can you try it out?
https://raw.githubusercontent.com/custom-cards/spotify-card/multi-account-support/dist/spotify-card.js

The additional configuration option is called `account` that you add the value that you have set for the account in spotcast (https://github.com/fondberg/spotcast).
Then it will try to use that account string when calling spotcast.start.

**Comment by fondberg** [comment]
I have now released v1.10 which should be able to work with different accounts in spotcast. Can you  please help me test it?

**Comment by ThirteenTX** [comment]
> 
> 
> I have now released v1.10 which should be able to work with different accounts in spotcast. Can you please help me test it?

I will try this out tonight! Thanks for this!

**Comment by ThirteenTX** [comment]
> 
> 
> I have now released v1.10 which should be able to work with different accounts in spotcast. Can you please help me test it?

Okay so I am a little late testing but this works! My wife can log into her spotify account on her phone or computer and use her stuff. Thanks for this!

**Comment by fondberg** [comment]
I'm closing this then. Great that it works
