### ISSUE TITLE
Spotify connect devices not showing up

### ISSUE THREAD

**Issue by lfotnhome** [custom-cards/spotify-card#37]
I've tried Shift F5, I've trued restarting the server, I've tried refreshing lovelace after I've started music on spotify from the web player. I don't know what else to try.  It is showing me my googlecast devices, but it won't even let me select them, and isn't showing any of my spotify connect devices (all of my Echo Dot's)
![image](https://user-images.githubusercontent.com/53139041/71163869-918ecf80-2213-11ea-897b-8e9825238fae.png)

**Comment by fondberg** [comment]
I think you might have been using different accounts for the card and the rest or else there is something fishy and you need to look in developer tools in your browser for the network requests to spotify and check k that it returns the data you expect

**Comment by flix4f** [comment]
I am experiencing something similar. My two Sonos players do not show. They are there in the Spotify desktop app on the same computer but not in the card. No difference whether I approch HA through the local address or via public address.
To be honest Sonos does not have the best track record with Spotify Connect, but is currently quite stable...

**Comment by flix4f** [comment]
> 
> 
> I am experiencing something similar. My two Sonos players do not show. They are there in the Spotify desktop app on the same computer but not in the card. No difference whether I approch HA through the local address or via public address.
> To be honest Sonos does not have the best track record with Spotify Connect, but is currently quite stable...

Now see in a post from August that is was mentioned and answered already...
