### ISSUE TITLE
incorrect redirect URI from component

### ISSUE THREAD

**Issue by sdekker90** [custom-cards/spotify-card#39]
During the initial setup, I encountered an incorrect redirect URI. When you get to the step where you click "Authenticate" in the component, I had to alter a part of the redirect uri manually to "lovelace/media". By default it said "lovelace/default_view". After manually changing the URI, the authentication worked fine.

**Comment by fondberg** [comment]
If you look at the spotify card, what is the URI then?

**Comment by sdekker90** [comment]
The URI in the address bar when viewing the spotify card was lovelace/default view. 

In the meantime I had to redo most of my Hass.io setup due to hardware failure, so I can no longer reproduce the issue.
