### ISSUE TITLE
Can't authenticate

### ISSUE THREAD

**Issue by parkkralle** [custom-cards/spotify-card#42]
After installation I only get the authenticate picture. 
![image](https://user-images.githubusercontent.com/59173472/73054034-aa7d4700-3e89-11ea-9ba9-15942a3259cf.png)

If I click on it the login window appears, then I will be forwarded to a page with the error message “INVALID_CLIENT: Invalid client”.
![image](https://user-images.githubusercontent.com/59173472/73054082-c8e34280-3e89-11ea-92f7-c8681f05f73b.png)

My configuration:
- Spotify Developer
![image](https://user-images.githubusercontent.com/59173472/73054145-ef08e280-3e89-11ea-8e4d-9169f4163fcc.png)

- Home Assistant
![image](https://user-images.githubusercontent.com/59173472/73054197-16f84600-3e8a-11ea-9da4-402c11b1b009.png)

![image](https://user-images.githubusercontent.com/59173472/73054223-29727f80-3e8a-11ea-84b9-1efc4dd4f956.png)

 What is wrong in my configuration?

PS:
The Spotify Player does work.
![image](https://user-images.githubusercontent.com/59173472/73054332-70607500-3e8a-11ea-8b50-333f0082e931.png)

Thanks for help!

**Comment by braxtondiggs** [comment]
I just had the same situation. I followed this [ticket](https://github.com/custom-cards/spotify-card/issues/39). I changed the callback in Spotify to https://(your public home assistant hostname):8123/lovelace/default and it worked

**Comment by matthewmarra** [comment]
Having the same issue.

**Comment by fondberg** [comment]
Hi, github issues are reserved for bug reports. Please ask your question in the community forum as I don't have time to provide individual support
