### ISSUE TITLE
Authenticate every time I open hass

### ISSUE THREAD

**Issue by tom-lejeune** [custom-cards/spotify-card#46]
Hi, thanks for the great card. It works fine now after understanding the URL I had to add in Spotify developer. However, I have to authenticate every time I open the page where my card is...
Is this normal behaviour?

Thanks!
Tom

**Comment by fondberg** [comment]
The authentication should be automatic and you should just see a brief flash of the page as it does a redirect of the browser page.the reason for this is that a spotify login token is only valid for 60 minutes. 

If this is not what happens, 0lease describe in detail what you are experiencing

**Comment by netracernz** [comment]
Hi, I have this same issue, I get an "Authenticate: button which then gives me the Spotify account login page which requires me to put in my username and password. after a certain about of time or if I close and reopen I have to redo the authentication.

**Comment by fondberg** [comment]
The card relies in local storage functionality in the browser. The browser needs to support this and any plugins to the browser which affects this need to be disabled.

What browser and plugins are you using?

**Comment by JeremyKennedy** [comment]
I have a similar issue, however it's not every time I open HA. It might be every time I restart HA? I need to do some more testing. 

It authenticates and redirects automatically, I never press the button. Most of the time it works, sometimes it says invalid redirect so I just press Back on my browser to get back to HA. 

Either way, error or not, the disruptive page loads are making me consider moving this card on to its own tab. I will try to follow up over the next week with better information. I'm using Firefox.

**Comment by fondberg** [comment]
Unfortunatly Spotify auth token for web clients requires an auth every 60 mins. That means a redirect of the entire page. The functionality required for the card should ideally be in HA and no direct communication with spotify apis should be done from the card but that is not the case today.
