### ISSUE TITLE
Support random_song: true from spotcast.start

### ISSUE THREAD

**Issue by starkillerOG** [custom-cards/spotify-card#49]
according to the readme file the Spotcast service is already supported by this custom card.
Would it be possible to have a optional card attribute: "random_song: true" that would then use the spotcast.start service always with the aditional option "random_song: true".

In that way a playlist can be started at a random position instead of always the first song.

**Comment by rhgiter** [comment]
miss random song - will it be possible?

**Comment by fondberg** [comment]
Everything is possible but in these corona times I have not had the time to do anything with the card. Volunteers could perhaps to it?

**Comment by jacobswe** [comment]
Fix was pretty simple, threw a pull request up adding another option to shuffle each time a playlist is played. In the meantime, editing your dist file to add 'random_song: true' works beautifully as an interim.

**Comment by fondberg** [comment]
Latest release adds option for random song but only for spotcast started playback.
