### ISSUE TITLE
wrong position of scrollbar on firefox

### ISSUE THREAD

**Issue by starkillerOG** [custom-cards/spotify-card#52]
In firefox since the last version release (1.22) the overflow on the list of playlists is broken (see picture)
In the previous version it did work (1.20).

![Spotify-card-firefox](https://user-images.githubusercontent.com/14811189/76367473-740e6500-632d-11ea-9992-7d940a6164d5.png)
(I have blanked out my playlists)

The scrollbar should not be at the outside along the whole thing but on the inside in the black squire to only scroll the playlist and not the whole card.
Now if you scroll the Spotify logo and selection of media player also scroll "away"

configuration:
```
      - client_id: ???
        height: 170
        limit: 25
        type: 'custom:spotify-card'
```

**Comment by fondberg** [comment]
Hmm, there was a firefox fix made by @exetico in https://github.com/custom-cards/spotify-card/pull/47 after 1.20. 
Maybe need to revert that unless @exetico can provide how he had setup his firefox card...

**Comment by exetico** [comment]
@starkillerOG I'm seeing no issues, what so ever. Which browser, are you using? Also, try with another theme (and the details one, if you're not using the details in the test). Also, if you have any Stylish scripts, CSS custom things or so, disable them too.

**Comment by starkillerOG** [comment]
I use firefox 74.0 (64-bits).
I only have issues when using the height option, otherwise it works fine.
I only use default theme and do not have style/css scripts.
I do have some custom plugins installed (all available on HACS):

- fold-entity-row
- Vertical Stack In Card
- Mini Media Player
- Start Spotify on chromecast
- Alexa Media Player

**Comment by starkillerOG** [comment]
just checked and I have the same problem in chrome browser

**Comment by starkillerOG** [comment]
@exetico I also uninstalled all my other custom plugins and re-installed spotify-card and then restarted HomeAssistant and the problem was still there.
(afterwards I reinstalled my custom plugins)

**Comment by starkillerOG** [comment]
@exetico @fondberg  I checked again and reverted to version 1.20 of spotify-card and that version works fine.
In version 1.21 and in version 1.22 this problem occurs.

**Comment by exetico** [comment]
It's odd, that it's working just fine here. Could it be related to a specific version of HA, too? I'm currently on Home Assistant 0.106.5, and waiting for the lastest versions, to be a bit more stable. A few mentioned bugs in 107.x, but i'm not sure if that's correct, or not. I could try and upgrade... 

Are you using a custom scaling/DPI for your monitor? What are the resolution, of the screen?

It's wierd...

**Comment by starkillerOG** [comment]
I am using HA v107.7 the latest.
@exitico are you also using the height option to make the card smaller than the number of playlists you have?

**Comment by starkillerOG** [comment]
checked on 2 diffrent computers, both have the same problem.
PC1: resolution 1920x1080 scaling 125% windows 10
PC2: resolution 1920x1080 scaling 100% windows 10

**Comment by exetico** [comment]
_I'm sorry for the slow replies._

I've just upgraded from 0.106.5 to the newests version.

But **no**, i'm not using the height-option, so that must be the problem. I totally missed that part, in your config.
![image](https://user-images.githubusercontent.com/3549445/78350309-48397480-75a5-11ea-8ea9-dfa60de4a732.png)

I guess the solution should be, to handle the styling two-way (if height is defined, or it's "auto"/undefined)

**Comment by starkillerOG** [comment]
@exetico I am glad we found the issue!
Would you be willing to implement the fix as you sugested?

**Comment by fondberg** [comment]
This is completely gone in the new version 2 which is out in beta
