### ISSUE TITLE
Position of menu fixed when height is set

### ISSUE THREAD

**Issue by daveonkels** [custom-cards/spotify-card#55]
When setting a height on a larger list I'm seeing the dropdown menu fixed in its original position (along with the background remaining the same size). The iframe scrolls, but the menu falls on top of the playlists themselves.

_Running Home Assistant 0.107.7 & 1.2.2 of spotify-card._

<img width="359" alt="ss-spotify" src="https://user-images.githubusercontent.com/533642/77664262-4a635980-6f3b-11ea-9386-cdf77ad50c65.png">

**Comment by fondberg** [comment]
Which OS, 
Browser and version
Themes for lovelace
style changes for lovelace
Are you using lovelace plugins to display this card

list goes on and on why style buges appear. So please remove all lovelace plugins and display this on a tab of itself and reproduce in a sensible browser (FF, Chrome)

**Comment by starkillerOG** [comment]
I think this is the same issue I have: https://github.com/custom-cards/spotify-card/issues/52

**Comment by fondberg** [comment]
You are probably right

**Comment by fondberg** [comment]
This should be solved in the version right?
