### ISSUE TITLE
transfer_playback no longer available in spotcast

### ISSUE THREAD

**Issue by fgccampos** [custom-cards/spotify-card#56]
As per https://github.com/fondberg/spotcast, transfer_playback is no longer available thus the spotify-card return the following error:
_extra keys not allowed @ data['transfer_playback']_
Could you make a small tweak to fix this? Thank you

**Comment by neomvll** [comment]
Always check change log, now is force_playback.

**Comment by ProLoser** [comment]
@neomvll this is a bug with spotify-card, these services are not being called directly

**Comment by fondberg** [comment]
right, forgot to change the card. Will do that today
