### ISSUE TITLE
Release numbers are all over the place

### ISSUE THREAD

**Issue by ProLoser** [custom-cards/spotify-card#58]
I am trying to build a well-formed PR to fix #56 and I don't get what your logic is with these versions:

1.11 -> 1.20 (instead of 1.12?)

Your package.json is still 1.11 (and your package-lock.json is 1.10)

https://github.com/custom-cards/spotify-card/releases shows you actually are up to 1.22?

I think you need to follow some consistent process when you cut a new release. I'm assuming you mark the version and tag when you merge to master.

**Comment by ProLoser** [comment]
To clarify, my fix would essentially be a PATCH level fix, so it should probably be 1.22.1 when you merge it in

**Comment by fondberg** [comment]
Sure! The card is indeed in need of some TLC ;-)
Will do a release today so I'll fix it so everything is 1.23

**Comment by ProLoser** [comment]
Are you not using it? When I tried using my card after the fix it still had
bugs. I had to change the decide twice for the card to reflect the changes.

**Comment by fondberg** [comment]
I am but not every day. I've been busy taking care of sick relatives

**Comment by ProLoser** [comment]
Understandable priorities

**Comment by fondberg** [comment]
This should be fixed in the new 1.24.0 release
