### ISSUE TITLE
Devices droplist should open UPWARDS

### ISSUE THREAD

**Issue by ProLoser** [custom-cards/spotify-card#60]
Right now my Spotify card is at the bottom edge of the screen. When you open the devices list, it creates a box that requires me to scroll down beyond the bottom edge of the dashboard to see the list of options.

I think the UX should be changed for the popup menu to be bottom-edge aligned with the bottom of the card

**Comment by Duke-Box** [comment]
I agree. It wrecks the UI of the particular view. If it opened over the spotify card container then that would at least mitigate the damage. 

Nice card BTW

**Comment by ProLoser** [comment]
You could put it in the top-right corner instead of bottom left

**Comment by Duke-Box** [comment]
Hi,
I actually have it as the only card on the view. So it is in the middle at
the top and the list of devices still causes the screen to scroll down. So
that doesn't help.
I could use the height: object to reduce the overall height of the card but
as noted in another 2 reported issues, that just breaks the cards UI.

I am on home assistant 107.7 and use both the latest versions of chrome and
edge ( it doesn't matter which ) with default theme. The card is pure
vanilla config with no style applied. I suspect the it's a 107.7 issue not
yours though, but........

Thanks

**Comment by fondberg** [comment]
As this is open source and completely free you are welcome to do that change and create a pull request.
I have the card top left so it is not a problem for me

**Comment by mattbruman** [comment]
I experienced the same thing, I do have it at the top but I have the issue because I have 20 devices and groups, I would much rather be able to exclude or favorite some speakers and groups, since I rarely ever play on individual speakers and mostly use groups. 
![image](https://user-images.githubusercontent.com/43623584/83972333-86a52580-a8ad-11ea-91b0-dafc41314e47.png)
