### ISSUE TITLE
Display incorrect when using 2 cards in same view

### ISSUE THREAD

**Issue by dlundgren44** [custom-cards/spotify-card#61]
When using this card twice on the same view the second instance shows big pictures instead of a list, making it hard to get an overview, see pcitures. 
Reason for using 2 cards on same view? I want to have one list with my top playlist, and one with the featured playlists.

I am using: 
homeassistant 0.107.7
Chrome  80.0.3987.149
ios dark theme for lovelace (but same problem for other themes as well)

![spotify issue](https://user-images.githubusercontent.com/50276825/77967355-3d50bc80-72e5-11ea-873b-65f97ff2b9b2.png)

**Comment by fondberg** [comment]
I have never tested 2 cards on the same tab but you are right it get messed up.
It is not easy to fix as there are several other things that will go wrong with having 2 cards on the same page. Sorry but the answer will have to be that it is not supported.

**Comment by dlundgren44** [comment]
No worries, not a crucial feature for me. Something for the future perhaps, but Ill get around it by using 2 seperate views for now :)
Thanks for the awesome card though!
