### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ikke68** [custom-cards/spotify-card#64]
Hi,

I've setup your'e awesome spotify card and you're spotcast plugin, know when  i put the card in a lovelace view and if i click on that that i get redirected to a page with something about a login url....
You have any idea what i did wrong? Below is my config. '
# spotify
spotify:
  client_id: !secret spotify_user
  client_secret: !secret spotify_passwd

# spotcast
spotcast:
  client_id: !secret spotify_user
  client_sectet: !secret spotify_passwd `

**Comment by fondberg** [comment]
This tracker is not for support. Please use the community forum for this. Hint is to read the documentation about the redirect url
