### ISSUE TITLE
transfer playback ? i got this error ? 

### ISSUE THREAD

**Issue by rhgiter** [custom-cards/spotify-card#65]
![image](https://user-images.githubusercontent.com/61065752/79012742-4c4a3100-7b67-11ea-8ba6-c30f3ba9457d.png)
![image](https://user-images.githubusercontent.com/61065752/79012746-4fddb800-7b67-11ea-99ee-715d46aa82bd.png)

**Comment by Maxbrand** [comment]
+1

**Comment by Maxbrand** [comment]
My error was showing up because I called on the resource using the CDN. When I changed to the local files the error was solved.

**Comment by fondberg** [comment]
great, that was fixed some releases ago
