### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by WirelessMind** [custom-cards/spotify-card#69]
Hello!
After a while I keep the Home Assistant page open (not necessarily where the Spotify card is located), the page reloads on a Spotify link indicating "INVALID_CLIENT: Invalid redirect URI".
Home Assistant must always remain open on that client. If this happens, I have to remove the card!
Thanks

**Comment by bgx4k3p** [comment]
I had the same issue, but noticed the redirect URL is different. There is an error in the instructions.

Change: https://<your public home assistant hostname>:8123**/lovelace/media** to https://<your public home assistant hostname>:8123**/lovelace/music** in the Spotify Developer app

Mine is working now

**Comment by WirelessMind** [comment]
Why if my path is different? mi path is https://domusaria.duckdns.org/lovelace-media/player

**Comment by WirelessMind** [comment]
Why if my path is different? mi path is https://<your public home assistant hostname>/lovelace-media/player

**Comment by bgx4k3p** [comment]
It looks like the naming convention is like this:
`https://<your public home assistant hostname>:<port>/<lovelace-dashboard-name>/<dashboard-tab-name>`

In your case you probably have dashboard with name `lovelace-media` and then tab called `player`. You might be missing the port number, try adding that:
`https://<your public home assistant hostname>:<add-port-here>/lovelace-media/player`

**Comment by WirelessMind** [comment]
No, mine is set up without the door. I use duckdns without a port.
In fact, if I add it to the url redirect, it doesn't really work.

**Comment by WirelessMind** [comment]
Nothing to do, the error persists.
For now I have to remove the card because it causes me problems.

**Comment by fondberg** [comment]
Please take help from the forum. It seems like you have not configured it correctly
