### ISSUE TITLE
No media players present

### ISSUE THREAD

**Issue by LDaneliukas** [custom-cards/spotify-card#7]
After adding the resource to lovelace-ui and the card, I'm seeing the following:
![image](https://user-images.githubusercontent.com/10710427/55828952-33530e00-5b16-11e9-9697-d7c818882449.png)
Note - I've tried clicking all around the card without any change)

Even though, checking the network tab in browsers console shows that the API request was successful and I have several active devices and playlists, e.g.:
![image](https://user-images.githubusercontent.com/10710427/55829015-58478100-5b16-11e9-955f-144f53e64d3d.png)

I tried clearing the browser cache and several browsers: Chrome, Firefox.

FYI, I'm using other Spotify integrations:
- SpotifyPlaylist Sensor - works fine, returns all playlists.
- Spotify media_player - works fine, detects media and can play media on active devices.

Each integration has a separate application created in the Spotify dev console and non of them share credentials.

Any ideas?

**Comment by fondberg** [comment]
The code for displaying devices has no filtering so I don't understand why you don't get any output.
I've created a debug build. Can you try with that and copy and paste the js console debug output?
https://github.com/custom-cards/spotify-card/releases/download/v1.3/spotify-card.umd-debug.js

**Comment by LDaneliukas** [comment]
Can't seem to download from GitHub: `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://github.com/custom-cards/spotify-card/releases/download/v1.3/spotify-card.umd-debug.js. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

**Comment by LDaneliukas** [comment]
Worked around CORS with DropBox:
```
SpotifyCard: playlists.length: 0  authenticationRequired: true  devices.length 0 spotify-card.umd-debug.js:25:2788
SpotifyCard: playlists.length: 0  authenticationRequired: false  devices.length 0 spotify-card.umd-debug.js:25:2788
PlayerSelect: devices 
Array []
spotify-card.umd-debug.js:1:81258
Response: playlists 
Array(10) [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…} ]
spotify-card.umd-debug.js:25:1396
Response: devices 
Array [ {…} ]
spotify-card.umd-debug.js:25:1433
SpotifyCard: playlists.length: 10  authenticationRequired: false  devices.length 1 spotify-card.umd-debug.js:25:2788
Unhandled promise rejection TypeError: "t.images[0] is undefined" spotify-card.umd-debug.js:1:41522
    render https://dl.dropboxusercontent.com/s/XX/spotify-card.umd-debug.js:41
    render https://dl.dropboxusercontent.com/s/XX/spotify-card.umd-debug.js:36
    wu https://dl.dropboxusercontent.com/s/XX/spotify-card.umd-debug.js:1
    eu https://dl.dropboxusercontent.com/s/XX/spotify-card.umd-debug.js:1
    a https://dl.dropboxusercontent.com/s/XX/spotify-card.umd-debug.js:1
    No https://dl.dropboxusercontent.com/s/XX/spotify-card.umd-debug.js:1
    i https://dl.dropboxusercontent.com/s/XX/spotify-card.umd-debug.js:1
```

**Comment by fondberg** [comment]
hey @LDaneliukas. Use this link https://cdn.jsdelivr.net/gh/custom-cards/spotify-card@master/dist/spotify-card.umd-debug.js

**Comment by jmheist** [comment]
stumbled on this issue as I just added this today and only get hassio as a mediaplayer option. not sure if related, but ran you debugger version and got this. hope it helps:

```
SpotifyCard: playlists.length: 0  authenticationRequired: true  devices.length 0
spotify-card.umd-debug.js:25 SpotifyCard: playlists.length: 0  authenticationRequired: false  devices.length 0
spotify-card.umd-debug.js:1 PlayerSelect: devices 
[]
length: 0
__proto__: Array(0)
spotify-card.umd-debug.js:25 Response: playlists 
(10) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
0: {collaborative: false, external_urls: {…}, href: "https://api.spotify.com/v1/playlists/4Kn7mhMvXxnXiHjalKOA9e", id: "4Kn7mhMvXxnXiHjalKOA9e", images: Array(3), …}
1: {collaborative: false, external_urls: {…}, href: "https://api.spotify.com/v1/playlists/4QATKqauZnYBZM0t19QFqq", id: "4QATKqauZnYBZM0t19QFqq", images: Array(3), …}
2: {collaborative: false, external_urls: {…}, href: "https://api.spotify.com/v1/playlists/5wLdsOyul46WgEV3jXGHZo", id: "5wLdsOyul46WgEV3jXGHZo", images: Array(3), …}
3: {collaborative: false, external_urls: {…}, href: "https://api.spotify.com/v1/playlists/0h1UEO7G7bKT91xH7K9nE0", id: "0h1UEO7G7bKT91xH7K9nE0", images: Array(3), …}
4: {collaborative: false, external_urls: {…}, href: "https://api.spotify.com/v1/playlists/3M72MhDVzFKrZrdTCwlEqv", id: "3M72MhDVzFKrZrdTCwlEqv", images: Array(3), …}
5: {collaborative: false, external_urls: {…}, href: "https://api.spotify.com/v1/playlists/111EcMAYJxiCUfm0z9Af6U", id: "111EcMAYJxiCUfm0z9Af6U", images: Array(3), …}
6: {collaborative: false, external_urls: {…}, href: "https://api.spotify.com/v1/playlists/37i9dQZEVXcTXdk0f09b8t", id: "37i9dQZEVXcTXdk0f09b8t", images: Array(1), …}
7: {collaborative: false, external_urls: {…}, href: "https://api.spotify.com/v1/playlists/7bICQfyhxQSSBpHVIMUcJ2", id: "7bICQfyhxQSSBpHVIMUcJ2", images: Array(3), …}
8: {collaborative: false, external_urls: {…}, href: "https://api.spotify.com/v1/playlists/2kPuCszlYTHRioxEmuZdh7", id: "2kPuCszlYTHRioxEmuZdh7", images: Array(3), …}
9: {collaborative: false, external_urls: {…}, href: "https://api.spotify.com/v1/playlists/4VALzvJJ1HlnMj3ojlfjEo", id: "4VALzvJJ1HlnMj3ojlfjEo", images: Array(3), …}
length: 10
__proto__: Array(0)
spotify-card.umd-debug.js:25 Response: devices 
[{…}]
0: {id: "Hass.io", is_active: false, is_private_session: false, is_restricted: false, name: "Hass.io", …}
length: 1
__proto__: Array(0)
spotify-card.umd-debug.js:25 SpotifyCard: playlists.length: 10  authenticationRequired: false  devices.length 1
spotify-card.umd-debug.js:1 PlayerSelect: devices 
[{…}]
spotify-card.umd-debug.js:25 SpotifyCard: playlists.length: 10  authenticationRequired: false  devices.length 1
spotify-card.umd-debug.js:1 PlayerSelect: devices 
[{…}]
0:
id: "Hass.io"
is_active: false
is_private_session: false
is_restricted: false
name: "Hass.io"
type: "Speaker"
volume_percent: 100
__proto__: Object
length: 1
__proto__: Array(0)
```

**Comment by fondberg** [comment]
@jmheist there is no apparent error in the log you sent. Dis the debug version work or not work?
If not, what is the symptom?

**Comment by jmheist** [comment]
@fondberg No errors, but maybe not working as I expected. I tried both versions, the debug, and the master, both versions only give me 'Hassio' as the speaker output. My issue is unrelated, and probably something I didnt setup or config that I should have. I'm new to HA :)

**Comment by LDaneliukas** [comment]
@fondberg  - oddly enough, it actually works fine with `https://cdn.jsdelivr.net/gh/custom-cards/spotify-card/dist/spotify-card.umd-debug.js` but it doesn't work (as described in the issue) with `https://cdn.jsdelivr.net/gh/custom-cards/spotify-card@1.3/dist/spotify-card.umd.js`.

**Comment by fondberg** [comment]
I see. Then I know what is wrong. I'll release a new version

**Comment by fondberg** [comment]
New release 1.4 made closing this
