### ISSUE TITLE
What values need to go into config?

### ISSUE THREAD

**Issue by jkoenig72** [custom-cards/spotify-card#70]
Hi, 

I get it running - nice project.   

Have a question around those paramters -

      featuredPlaylists: <optional show featured playlists instead of users playlists>
      dailyMixes: <optional show daily mixes, requires spotcast>

What format goes in here? How I can select and present a featured playlist here?

Like 'spotify:playlist:37i9dQZF1DXaIrEwuQ3hyy' or how does that work? Can somebody share a complex config? 

Thanks!
Joerg

**Comment by fondberg** [comment]
These are true or false but dailyMixes are not working at the moment due to issues with spotcast
