### ISSUE TITLE
two playlists on same dashboard?

### ISSUE THREAD

**Issue by mattbruman** [custom-cards/spotify-card#76]
I tried to create both cards on the same dashboard but the formatting is messed up when having both custom playlists and mixes, is there something i'm missing here?

client_id: ID
name: Spotify 1
id: 211
dailyMixes: true
device: null
featuredPlaylists: null
featuredPlaylistsCountryCode: us
height: 240
limit: 20
player: null
random_song: null
type: 'custom:spotify-card'
- client_id: ID
name: Spotify 2
dailyMixes: false
device: null
featuredPlaylists: null
featuredPlaylistsCountryCode: us
height: 720
limit: 20
player: null
random_song: true
type: 'custom:spotify-card'

**Comment by fondberg** [comment]
There was old ticket about this and there I said it is not possible to have them on the same page unfortunately.
