### ISSUE TITLE
URL Redirect error when on a different pane

### ISSUE THREAD

**Issue by Warlord1390** [custom-cards/spotify-card#77]
I found that when I leave my HA running on a different pane than the one with the spotify card the URL redirect for the card tries to resolve on the local url /lovelace/security or /configuration for example. 

My thought is that the card should only have the URL Redirect going to the page it is located on.

**Comment by fondberg** [comment]
I can not reproduce this. What browser are you using and how do you reproduce it?

**Comment by Warlord1390** [comment]
I ended up rebuilding my HA instance and the issue has disappeared, I was using chrome for reference and letting it sit on any other page than my media dashboard where it was located. I suspect the old HA instance had issues.

**Comment by FL550** [comment]
I've also ran into this issue today. I'll have a look into this in the next days and see if I can reproduce this consistently and fix it then.

**Comment by fondberg** [comment]
I'm working on a version which doesn't use spotify web api directly but rather uses spotcast and spotify media player in hass. That would fix this for sure as it doesn't need any own auth

**Comment by fondberg** [comment]
This is completely gone in the new version 2 which is out in beta

**Comment by TekniskSupport** [comment]
I can confirm that this issue has been solved as of the release of the 2.0 version (and was fixed in the beta as well)
