### ISSUE TITLE
Customize the amount?

### ISSUE THREAD

**Issue by gbdavidx** [custom-cards/spotify-card#8]
I love this card, and got it to work, but can i make a request so that it only displays the top 5?  I use it on an ipad and i can't have more then 2 columns

**Comment by fondberg** [comment]
Sure. Can you open an issue on the github repo so I don't forget?

Den mån 29 apr. 2019 05:52gbdavidx <notifications@github.com> skrev:

**Comment by gbdavidx** [comment]
thats what i did...

**Comment by fondberg** [comment]
My bad. I'll fix next time I have some time over

**Comment by gbdavidx** [comment]
can you have two redirect URLs in spotify?

**Comment by fondberg** [comment]
If you mean adding the card in two places it is supported with adding both redirect urls in spotify dev console

**Comment by fondberg** [comment]
Added a `limit` option in v1.5
