### ISSUE TITLE
Can't chose playlist

### ISSUE THREAD

**Issue by firstdominator** [custom-cards/spotify-card#81]
Always plays the first playlist on the list and can't change it.

**Comment by fondberg** [comment]
Which browser, version and os?

**Comment by firstdominator** [comment]
Chrome on Windows 10 Pro

**Comment by firstdominator** [comment]
Any updates on this? I updated to version 1.27 but still same issue.

Thanks!

**Comment by fondberg** [comment]
I haven't had time to debug this.  
Questions:

1. Is it a chromecast device or a spotify connect one?
2. What happens when you click another playlist two times? Can you send me the logs from the javascript console?

**Comment by firstdominator** [comment]
1. Chormecast device.
2. If I click twice I see the play button turn green. But it stays green for 2 seconds then no more green and first playlist  play button turns back green. But audio plays continuously without interuption between clicks, the same first playlist.

where can I find th ejavascrpit console?

Thanks for your time on this.

**Comment by dllaurent** [comment]
Hello,
I have the same problem.
in Chrome console, it say 
`SpotifyCard.js:168 Will not play because there is no playlist or device selected`
thank you, have a nice day.

**Comment by fondberg** [comment]
This is completely gone in the new version 2 which is out in beta

**Comment by firstdominator** [comment]
Weird... installed version 2 beta and still same issue.. I'm thinking it's something on my end.. not sure what to check..

**Comment by firstdominator** [comment]
After further investigation and not sure if this is how it should work.

I double click on a different playlist - nothing happens , same behaviour as before.
BUT
If I double click and then rechoose the same cast device IT WORKS!.
Not sure if that is how it's supposed to be. I taught that when you double click on the playlist it should automatically start that playlist without having to rechoose the cast device.

Let me know Thanks!

**Comment by firstdominator** [comment]
In the chrome console I get this error mesage when just double clicking on a playlist. 

Before double clicking I aleready have a device playing music.

SpotifyCard.js:168 Will not play because there is no playlist or device selected, null {id: "8e638bc670dc086eef71ba54472cb41b", is_active: true, is_private_session: false, is_restricted: false, name: "Living Room Google Home", …}
playPlaylist @ PlayerSelect.js:116
onPlaylistSelect @ PlayerSelect.js:116
(anonymous) @ SpotifyCard.js:259
k @ spotify-card.js:1
SpotifyCard.js:171 PUT https://api.spotify.com/v1/me/player/play?device_id=8e638bc670dc086eef71ba54472cb41b 403

**Comment by fondberg** [comment]
Hi! This is from version 1.

**Comment by firstdominator** [comment]
Installed v2-Beta.2 and acting like the last post I sent.

**Comment by firstdominator** [comment]
SpotifyCard.js:168 Will not play because there is no playlist or device selected, null {id: "8e638bc670dc086eef71ba54472cb41b", is_active: true, is_private_session: false, is_restricted: false, name: "Living Room Google Home", …}id: "8e638bc670dc086eef71ba54472cb41b"is_active: trueis_private_session: falseis_restricted: falsename: "Living Room Google Home"type: "CastAudio"volume_percent: 14__proto__: Object
playPlaylist @ PlayerSelect.js:116
onPlaylistSelect @ PlayerSelect.js:116
(anonymous) @ SpotifyCard.js:259
k @ spotify-card.js:1
SpotifyCard.js:171 PUT https://api.spotify.com/v1/me/player/play?device_id=8e638bc670dc086eef71ba54472cb41b 403

**Comment by firstdominator** [comment]
Thanks for all your efforts on this.

**Comment by fondberg** [comment]
I think there is some issue with hacs because that is not v2.

**Comment by firstdominator** [comment]
Thanks everything is working good now!.

Sorry for not getting back earlier I'll make sure to pay you some coffees.
