### ISSUE TITLE
Chromecast devices not displayed in dropdown

### ISSUE THREAD

**Issue by AdrinkBeer** [custom-cards/spotify-card#82]
Card version : 1.26 (I also tested with some previous version, same behavior)
Tested on FF and Chrome

My Chromecast devices are not available anymore in the dropdown : 

![image](https://user-images.githubusercontent.com/39377916/85552701-90f04f00-b623-11ea-86ea-fd7e216667aa.png)

If I switch to edit mode of Lovelace, I can see my devices : 

![image](https://user-images.githubusercontent.com/39377916/85553384-2ee41980-b624-11ea-9282-73f3e3c91eda.png)

I noticed an error in the console of the browser (only when devices are not displayed) : 
```
Cannot read property 'callWS' of undefined
Uncaught (in promise) TypeError: this.props.hass is undefined
    refreshCastEntities http://ip/hacsfiles/spotify-card/spotify-card.js:1
    componentDidMount http://ip/hacsfiles/spotify-card/spotify-card.js:1
    w http://ip/hacsfiles/spotify-card/spotify-card.js:1
    ...
```

I suppose that the issue is about timing ?

Thank you for your work :)

**Comment by fondberg** [comment]
That should be sent in from lovelace. What version of HA are u running?

**Comment by AdrinkBeer** [comment]
I'm running version 0.111.4

Le mer. 24 juin 2020 à 21:10, Niklas Fondberg <notifications@github.com> a
écrit :

**Comment by fondberg** [comment]
You have something weird in your setup I think. It works fine for others with 0.111.4.
Which browser?

**Comment by AdrinkBeer** [comment]
Sorry, I tested a little bit more and I am able to add more information.
I tested on FF, Chrome and Edge (Chromium).

The situation : A second dashboard with only 3 cards in a vertical-stack : 2 custom:mini-media-player and the spotify-card.
When I use the spotify card outside the stack, it works as expected, but inside the stack, I get the behavior described in this issue.

**Comment by fondberg** [comment]
In that case you need to report this to the maintained I'd the wrapped card vertical stack
