### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by finnie2006** [custom-cards/spotify-card#83]
it is not working it sas 
Cannot read property 'setConfig' of undefined

**Comment by fondberg** [comment]
Please add more information. Versions, how did you install it. Complete console.log

**Comment by finnie2006** [comment]
oke what i did i maded a project in the spotify developer console with the redirecting url but i dont know where you need to set
  - type: module
    url: >-
      https://cdn.jsdelivr.net/gh/custom-cards/spotify-card@1.25.0/dist/spotify-card.umd.js
where do you need to put that

**Comment by finnie2006** [comment]
??? can you help me

**Comment by finnie2006** [comment]
I have been working on it for a few hours but it just doesn't work. The explanation is also very short

**Comment by FL550** [comment]
If you are not using hacs for installing, you have to enable advanced mode for Lovelace in your user settings. Then you can add custom resources in the settings. But I would suggest you use HACS.

**Comment by finnie2006** [comment]
i have hacs and the spotify card installed but how do i get the card on my lovelace

**Comment by finnie2006** [comment]
I have progressed I have set the spotify card and installed spotcast and the sp dc and sp key but cannot select a chromecast yet, did I forget to set something?

**Comment by finnie2006** [comment]
I finally succeeded thanks to the people who helped me
