### ISSUE TITLE
No playlist(s) shown when setting dailyMixes parameter

### ISSUE THREAD

**Issue by keigezellig** [custom-cards/spotify-card#84]
When i set the dailyMixes parameter in the configuration to true, the playlists won't show up.
I use HAS 0.111 with the Spotify-card and spotcast addons installed through HACS

**Comment by fondberg** [comment]
Have you configured spotcast?

**Comment by keigezellig** [comment]
Yes, i have. My 'normal' playlists DO show up and i can play music through my chromecast devices

**Comment by fondberg** [comment]
Weird. As i don't have your account I can't help you because it works for me and many others

**Comment by mattbruman** [comment]
Same issue here, no facebook integration, updated HA and supervisor last night and the lists are no more.

`client_id: redacted
dailyMixes: true
device: media_player.kitchen_dining_group
featuredPlaylists: null
featuredPlaylistsCountryCode: us
height: 350
id: 211
limit: 20
name: Spotify 1
player: null
random_song: null
type: 'custom:spotify-card'`

**Comment by fondberg** [comment]
I will test with upgrading HA tomorrow

Which versions of HA and spotcast are you using?

**Comment by fondberg** [comment]
I just tested this as well as a friend on mine and it works. You must have some problems with spotcast or your account

**Comment by fondberg** [comment]
Should be fixed in new version
