### ISSUE TITLE
Multiple accounts?

### ISSUE THREAD

**Issue by HorizonKane** [custom-cards/spotify-card#86]
Hi,

Is it possible to use this card with multiple accounts in any way (either switching between the playlists or merge them)?

Or even being able to have a second card with another account would be great.

Kind regards

**Comment by fondberg** [comment]
I prepared for it but haven't tested because I don't have 2 accounts. Please test and report back

**Comment by HorizonKane** [comment]
I just added a second card but it took the same account. Can I specify the account to use in the card? Because the card takes only the developer ID how it looks to me. For spotcast I differentiate the accounts through the cookie data and the spotify integration allows me to register two accounts.

However it is not necessary to invest much work if I am the only one asking for it, I found another way with mini-media-player buttons ;) But if you need somebody to test I am happy to help.

**Comment by fondberg** [comment]
You can now do that easily with the new card version 2 which is out in beta

**Comment by davidrustingha** [comment]
Okay, so I've been trying the multiple accounts function. I had some trouble setting it up:

At first it didnt show the custom card in the UI, which made it quite difficult to set it up properly.  It looked like it had the old colors and such.
Suddenly it showed up in the UI card picker. I was able to set it up, and in the visual editor it looked good! I saw 2 diffrent accounts with the coresponding playlists.
![Screenshot_2](https://user-images.githubusercontent.com/62120423/88042486-48f21880-cb4c-11ea-81de-0144170428c0.jpg)

When I clicked save it disappeared, and now it looks like this:
![Screenshot_1](https://user-images.githubusercontent.com/62120423/88042180-ce28fd80-cb4b-11ea-869a-add8cca0ce4a.jpg)

After I saved the first time and hit edit again I noticed the account selection doesnt work properly: When I select account A on the first card, it switches to account A on the second card too. And after saving it goes back to the default account.

It also looks like it only gives the error 'Spotify integration has to be installed for playback information' when the card(s) are placed inside a horizontal/vertical stack card.

**Comment by fondberg** [comment]
Right.. maybe the conf is sharded in lovelace. Need to check that

**Comment by davidrustingha** [comment]
Also: the spacing in the first picture (account B) looks off but thats just the wife's playlist naming. Too damn long..

**Comment by fondberg** [comment]
I tried 2 cards now and it works for me. I run without any card or theme tweaking addons with Chrome.

**Comment by davidrustingha** [comment]
The Android app:
I updated the card, and sometimes it works immediately after loading the dashboard, sometimes I have to reload the page a couple of times before it does

Chrome:
Same story. Sometimes reloading the page, sometimes switching to and back from another tab on the dashboard and then it works.

**Comment by davidrustingha** [comment]
I only have them in a horizontal stack, no card modded or anything. No theme customisation within the card itself too

**Comment by fondberg** [comment]
Can you try a fresh browser with no cache or history? Like firefox or safari or edge?

**Comment by davidrustingha** [comment]
Sure. Didn’t use Firefox yet so I installed that. Same thing. Entering the right tab it doesn’t load, clicking another tab and then the tab with the cards they do load

**Comment by davidrustingha** [comment]
In the app the cards load immediately but still give the ‘Spotify integration has to be installed’ error.

**Comment by fondberg** [comment]
That (spotify integration warning) should be solved in the latest release. Can you test that?

**Comment by davidrustingha** [comment]
Updated the card and spotcast, restarted HA and it loaded perfectly in the app and on chrome. 
The only thing that didn’t immediately load was the old Android tablet running Opera I use as a wall panel. But it’s not a problem for me, since I rarely refresh that page and it’s an easy fix. Thanks for all the work!

**Comment by fondberg** [comment]
Great!
