### ISSUE TITLE
Don't trust entity IDs

### ISSUE THREAD

**Issue by TekniskSupport** [custom-cards/spotify-card#92]
The code assumes that an entity id begins with "media_player.spotify_", but the id is changable by user, you shouldnt trust this.
Also this was not true for older versions of the spotify integration (before it had support for multiple instances, there was only one media player and it was called media_player.spotify. So this will break in older installations

https://github.com/custom-cards/spotify-card/blob/5e7c24e8f7cf28fcd2626d6f51de2d6b9b32c2cd/src/spotify-card.ts#L88

**Comment by fondberg** [comment]
Added an option in beta17(in the config gui or yaml) called `spotify_entity` where yo can define the entity id for spotify

**Comment by fondberg** [comment]
Should be fixed in latest release
