### ISSUE TITLE
Spotify Connect device ‘Home-Assistant’ doesn’t show

### ISSUE THREAD

**Issue by davidrustingha** [custom-cards/spotify-card#97]
**Describe the bug**
I set up spotcast and the Spotify card. Because I recently moved from a VM to an Ubuntu desktop Versio, I was able to add the spotify connect integration. It doesn’t show up in the Spotify card, but when I start playing music through the Spotify app on my HA it does show up.

* [X] Reproducable on a plain lovelace panel without card, style or theme mods
* [X] Using latest version of spotcast and spotify-card [X]
* [X] Using latest stable version of Home Assistant
* [X] I have Spotify Premium
* [X] I have setup the Spotify integration in Home Assistant

**To Reproduce**
Go to lovelace, ADD spotify card.
Home Assistant doesn’t show up as Spotify connect device. However, if I check Spotify on my phone it does show up.

**Expected behavior**
I expected to see Home Assistant as a Spotify connect device.

**Screenshots**
![image](https://user-images.githubusercontent.com/62120423/90168244-1cbd6680-dd9d-11ea-9ffe-28103bcd040c.png)

**Environment (please complete the following information):**
 - OS: [iOS, Android, Linux]
 - Browser: [chrome, safari]
 - Version: [latest]
 - HA version: [latest]
 - spotcast version: [latest]

**Configuration**
Add your configuration

**Additional context**

**Comment by FL550** [comment]
I think this might be related to spotcast.

**Comment by davidrustingha** [comment]
I think it might be caused by Spotcast too. My log fills with errors like:

```
2020-08-13 15:32:40 DEBUG (SyncWorker_7) [custom_components.spotcast] websocket_handle_devices msg: {'type': 'spotcast/devices', 'account': 'david', 'id': 57}
2020-08-13 15:32:40 DEBUG (SyncWorker_7) [custom_components.spotcast] setting up with  account david
2020-08-13 15:32:40 DEBUG (SyncWorker_7) [custom_components.spotcast] expires: 1597329146
```
I have renewed the sp_dc and sp_key already for all accounts, but the error still shows.

**Comment by fondberg** [comment]
It is because the Spotify integration only shows up as a connect device when it is playing because it borrows the credentials from your app.
So you need to check if it is possible to give it the login credentials so it shows up all the time.

I use librespot thru raspotify and theere it is possible.

**Comment by davidrustingha** [comment]
Aahhhh! Stupid me, I didn’t read the info because I thought that I only had to set-up a name and bitrate. Turns out I can set a username and password and now it shows up! 
Sorry for the trouble guys. I’ll close this issue 😂
