### ISSUE TITLE
Hardcode per card the player

### ISSUE THREAD

**Issue by MagicMicky** [custom-cards/spotify-card#98]
My use case is I basically use one tab per room to control, and would like that the `spotify-card` on the tab only controls one specific player.

On top of my use case, I feel this will have as an advantage that there will be no need to load all devices every-time you open the tab (This sometimes seems to bug where I see a "No device found" for some reason). We could hardcode the entities used on the card itself, and only the playlists will need to be fetched

Not sure if this is the best place to suggest a feature but thought I'd try.

My Typescript skills are a bit outdated but might be able to help out if you can point me in the general direction.

**Comment by FL550** [comment]
Hey, yes this is the right place for a faeture suggestion! But isn't your use-case covered with the `default_device` setting?

**Comment by MagicMicky** [comment]
The main issue i see with the default_device is that sometimes I still get a "No device found" for no specific reason. Refreshing usually solves it, but I think having it "enforced" would skip the fetching of device all together and I would never see this error. But maybe I'm making assumptions about this specific error and there's other ways to solve it.

**Comment by FL550** [comment]
Hm, when the "No device found" is shown, spotcast isn't able to detect any devices so forcing playback doesn't mean this is going to work. Maybe a regular check for new devices is a better option.

**Comment by MagicMicky** [comment]
Mmh more regular checks might indeed help;

Is there anyway to cache data from a card? Because caching the players (and the playlists) might help as well; ie: if no device found serve the cache?

**Comment by FL550** [comment]
Caching is not an option, as spotcast still needs the connection to the devices. We are on the regular checks, keep you informed!

**Comment by fondberg** [comment]
Is the device you want to have shown/pre-selecred a cast device or a spotify xonnected device?

Remember that a cast device will only appear as a connected device if Spotify is running in it

**Comment by MagicMicky** [comment]
Yeah the device preshown would be a Chromecast device/group.

My idea is that since I can use `spotcast.start` targeting my chromecast directly, and that I'm using one player per card, there's no need to fetch players from anywhere and just use the hardcoded ID that I pass it.

I basically want to have a list of playlist, and based on the card, where I click on the playlist it will use `spotcast.start` to the hardcoded device.

But this might be quite an edge case. If that's the case I'd already be happy with less `No device found` errors if it can be solved by more checks!

**Comment by fondberg** [comment]
Default device should work for this. If a csst device doesn't show up it is either a bug or it is lost in the HA state.

**Comment by MagicMicky** [comment]
I'll try to screenshot next time I see it happen if it can help bring more visibility on my issue

**Comment by MagicMicky** [comment]
FYI over the last few days and with the latest updates I've seen a lot of improvements here. I haven't had the problem mentioned abova happening, so I think it might makes sense to close this issue!

**Comment by FL550** [comment]
Nice and thanks for the feedback!
